# #+LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \pgfplotsset{compat=1.8}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}

#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [table]
# #+LaTeX_CLASS_OPTIONS: [bigger]
#+latex_header:  \mode<article>{\usepackage{beamerarticle}}
# #+latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# #+latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  线性离散系统分析
#+latex_header: \subtitle{离散系统稳定性}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:









* 稳定性
** S域到Z域的映射
*** $S\leftrightarrow Z$			      :BMCOL:B_ignoreheading:
      :PROPERTIES:
      :BEAMER_col: 0.5
      :BEAMER_env: ignoreheading
      :END:
\begin{eqnarray*}
z & = & e^{sT}\\
s &=& \sigma+j\omega \\
z &=& e^{\sigma T}e^{j\omega T} \\
|z| &=& e^{\sigma T} \\
\angle z &=& \omega T
\end{eqnarray*}
**** 当  $\sigma=0$  时,					    :B_block:
      :PROPERTIES:
      :BEAMER_env: block
      :BEAMER_envargs: <2->
      :END:
对应到  $z$  平面的单位圆,此时,  $\omega$  从  $-\infty\rightarrow\infty$ 时,  $z$  平面上的点己绕单位圆运动了无数圈,称  $[-\frac{\omega_s}{2},\frac{\omega_s}{2}]$  为主要带.

*** 主要映射关系:					      :BMCOL:B_block:
      :PROPERTIES:
      :BEAMER_col: 0.5
      :BEAMER_env: block
      :BEAMER_envargs: <3->
      :END:
 * 等  $\sigma$  线: 圆:   $|z|=e^{\sigma T}$ 
 * 等  $\omega$  线: 过原点射线:  $\angle z=\omega T$ 
 * 等  $\xi$  线(S平面过原点射线): 对数螺线

** 离散系统的稳定性
 * 稳定性定义:离散系统在有界输入序列下,输出序列也有界.
 * <2->连续系统中:闭环系统的特征根实部 $\sigma$  小于0.
 * <3->离散系统中:  $|z|<1$ ,($|z|=e^{\sigma}$)
   * 差分方程:特征根的模均小于1
   * 闭环脉冲传递函数:离散系统闭环特征根在Z平面的单位圆内($|z_i|<1$)
* 稳定性判据
\mode<article>{解特征方程,根据 $|z_i|<1$ 判断}
** W域的劳斯判据
  * Z域变换到W域:
      \begin{eqnarray*}
       z & = & x+jy\\
       w &= & u+jv \\
       z & = &\frac{w+1}{w-1} \\
       w &= & \frac{z+1}{z-1} \\
      \end{eqnarray*}
  * <2->等价关系:
      \begin{eqnarray*}
      u+jv &=& \frac{x^2+y^2-1-2yj}{(x-1)^2+y^2} \\
      |z|<1 &\Leftrightarrow& u<0 
      \end{eqnarray*}
 * <3->可在W域中使用Routh判据.
** W域的劳斯判据示例:

\begin{tikzpicture}[node distance=2.2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$r(t)$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$   $ ,right =of r] (p1) {}; 
\path[->](r) edge node {} (p1) ; 
\path[->] node[minimum size=2em,right =of p1] (s1) {}; 
\draw (s1.west)--(s1.north east);\draw[->] (s1.north west) arc (70:0:1.7em);\draw (s1.south) node {$T$};%\draw (s1.north) node[above] {$S$};
\path[](p1) edge node[midway] {$e(t)$} (s1) ; 
%\path[red,->] node[draw, inner sep=5pt,right =of s1] (g1) {$G_h(s)$}; 
%\path[->] (s1) edge node[midway] {$r^*(t)$} (g1); 
\path[red] node[draw, inner sep=5pt,right =of s1] (g2) {$\frac{k}{s(1+0.1s)}$}; 
\path[->] (s1) edge node[midway] {$e^*(t)$} (g2); 
\path[->] node[ right =of g2] (o) {$c(t)$}; 
\path[->] (g2) edge node {} (o); 
\path[->] node[minimum size=2em,above =of o] (sc) {}; 
\draw[dashed] (sc.west)--(sc.north east);\draw[dashed,->] (sc.north west) arc (70:0:1.7em);\draw[dashed] (sc.south) node {$T$};%\draw (sc.north) node[above] {$S$};
\path[dashed,draw](o.west)+(-1em,0) |- (sc.west) ; 
\path node[ right =of sc] (c) {$c^*(t)$}; 
\path[dashed,->] (sc) edge node {} (c); 
\path[red] node[ inner sep=5pt,below =of g2] (h) {$ $}; 
\path[draw] (g2.east)+(1em,0) |- (h.west);
\path[->,draw] (h.west) -| node [very near end] {$-$} (p1);
%\path[->, draw] (g.east)+(1em,0) -- +(1em,-3em) -| node[very near end] {$-$} (p1); 
\path[->] node[minimum size=2em,above =of p1] (sr) {}; 
\draw[dashed] (sr.west)--(sr.north east);\draw[dashed,->] (sr.north west) arc (70:0:1.7em);\draw[dashed] (sr.south) node {$T$};%\draw (sr.north) node[above] {$S$};
\path[dashed,draw](r.east)+(1em,0) |- (sr.west) ; 
\path node[ right =of sr] (i) {$r^*(t)$}; 
\path[dashed,->] (sr) edge node {} (i); 
\end{tikzpicture} 

分有无采样开关($T=0.1s$)两种情况分析使系统稳定的 $k$ 需要满足的条件.

*** 解:								    :B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :BEAMER_envargs: <2->
    :END:
 无采样开关时:
  \[D(s)=0.1s^2+s+k\]
  得:  $k>0$ 
** W域的劳斯判据示例(续):有采样开关时:
\begin{eqnarray*}
G(z) &=  &{\cal Z}[\frac{k}{s(1+0.1s)}] 
  = \frac{0.632kz}{z^2-1.368z+0.368} \\
\Phi(z) &=& \frac{G(z)}{1+G(z)}
\end{eqnarray*}
\begin{eqnarray*}
D(z) &=& z^2+(0.632k-1.368)z+0.368\\
z &=& \frac{w+1}{w-1} \\
D(w) &=& 0.632kw^2+1.264w+(2.736-0.632k)
\end{eqnarray*}
** W域的劳斯判据示例(续):有采样开关时:
 * Routh表:
     \[\begin{matrix}
     w^2 & 0.632k & 2.7360-0.632k \\
     w^1 & 1.264  & 0 \\
     w^0 & 2.736-0.632k
     \end{matrix}\]
 * 得:
     \begin{eqnarray*}
     0.632k &>  & 0\\
     2.736-0.632k& >& 0
     \end{eqnarray*}
 * 得:  
     \[0<k<4.33\]
 * <2->采样开关对稳定性有很大影响.
* 离散系统稳定性影响因素
** 离散系统稳定性影响因素
    * <2->系统开环增益
	*  $k\uparrow$  则离散系统稳定性下降
	*  $k\downarrow$  则离散系统稳定性提高
    * <3->采样周期
	*  $T\uparrow$  则离散系统稳定性下降
	*  $T\downarrow$  则离散系统稳定性提高
