# #+LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}

#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [table]
# #+LaTeX_CLASS_OPTIONS: [bigger]
#+latex_header:  \mode<article>{\usepackage{beamerarticle}}
# #+latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# #+latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 3
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  线性离散系统分析
#+latex_header: \subtitle{离散系统介绍}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* 离散系统基本概念
** 特点
*** 离散系统与离散信号
 * <2->离散系统:控制系统中有一处或几处信号是一串脉冲或数码
 * <3->离散信号:脉冲或数码(数字信号)
** 采样控制系统
*** 采样控制系统
 * <2->采样: 连续信号转变为离散脉冲序列的过程
    * <3->周期采样:离散信号的获取是周期性的
    * <4->非周期采样:离散信号的获取是非周期的
 * <5->复现:把脉冲序列转变为连续信号的过程
**** 连续信号						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[grid=both]
\addplot+[smooth,mark=none] plot coordinates
    {(0,2) (0.1,1) (0.3,0.5) (0.35,4) (0.5,3)
     (0.6,2) (0.7,1.5) (1,1.5)};
\end{axis}
\end{tikzpicture}
**** 采样:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[grid=both]
\addplot+[ycomb] plot coordinates
    {(0,2) (0.1,1) (0.3,0.5) (0.35,4) (0.5,3)
     (0.6,2) (0.7,1.5) (1,1.5)};
\end{axis}
\end{tikzpicture}
**** 复现:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :BEAMER_envargs: <5->
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[grid=both]
\addplot+[const plot] plot coordinates
    {(0,2) (0.1,1) (0.3,0.5) (0.35,4) (0.5,3)
     (0.6,2) (0.7,1.5) (1,1.5)};
\end{axis}
\end{tikzpicture}
*** 采样器与保持器
  * 典型采样控制系统中既有连续的模拟信号,又有离散的脉冲信号,因此需要:
       * 采样器: 模拟信号转换为脉冲信号
       * 保持器: 脉冲信号转换为模拟信号

\begin{tikzpicture}[node distance=2.2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$r(t)$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$   $ ,right =of r] (p1) {}; 
\path[->](r) edge node {} (p1) ; 
\path[->] node[minimum size=2em,right =of p1] (s) {}; 
\draw (s.west)--(s.north east);\draw[->] (s.north west) arc (70:0:1.7em);\draw (s.south) node {$T$};\draw (s.north) node[above] {$S$};
\path[](p1) edge node[midway] {$e(t)$} (s) ; 
\path[red,->] node[draw, inner sep=5pt,right =of s] (gh) {$G_h(s)$}; 
\path[->] (s) edge node[midway] {$e^*(t)$} (gh); 
\path[red,->] node[draw, inner sep=5pt,right =of gh] (gp) {$G_p(s)$}; 
\path[->] (gh) edge node[midway] {$e_h(t)$} (gp); 
\path[->] node[ right =of gp] (o) {$c(t)$}; 
\path[->] (gp) edge node {} (o); 
\path[blue,->] node[draw, inner sep=5pt,below =of gh] (h) {$H(s)$}; 
\path[->, draw] (o.west)+(-1em,0) |-   (h.east); 
\path[->, draw] (h.west) -| node[very near end] {$-$} (p1); 
%\path[->, draw] (g.east)+(1em,0) -- +(1em,-3em) -| node[very near end] {$-$} (p1); 
\end{tikzpicture} 

 *  $e^*(t)$  :采样信号
 *  $G_h(s)$  :保持器
 *  $e_h(t)$  :复现信号
 *  $S$  :理想采样开关
 *  $T$  :采样周期

** 数字控制系统
*** 数字控制系统
 * 以数字计算机作为控制器控制连续对象
 * 系统中既有连续信号,又有数字信号,实现两种信号之间的转换装置为A/D,D/A.
*** 模数转换器(A/D)
  * 将连续信号转换为数字信号.
  * <2->工作过程:
     * <2->采样过程:  $e(t)\rightarrow e^*(t)$ 
     * <3->量化过程:  $e^*(t)\rightarrow \bar{e}^*(t)$ 
**** 连续信号						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[grid=both]
\addplot+[smooth,mark=none] plot coordinates
    {(0,2) (0.1,1) (0.3,0.5) (0.35,4) (0.5,3)
     (0.6,2) (0.7,1.5) (1,1.5)};
\end{axis}
\end{tikzpicture}
**** 采样:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[grid=both]
\addplot+[ycomb] plot coordinates
    {(0,2) (0.1,1) (0.3,0.5) (0.35,4) (0.5,3)
     (0.6,2) (0.7,1.5) (1,1.5)};
\end{axis}
\end{tikzpicture}
**** 量化:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :BEAMER_envargs: <3->
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[grid=both]
\addplot+[ycomb] plot coordinates
    {(0,2) (0.1,1) (0.3,1) (0.35,4) (0.5,3)
     (0.6,2) (0.7,2) (1,2)};
\end{axis}
\end{tikzpicture}

*** 数模转换器(D/A)
  * 将离散的数字信号转换为连续模拟信号
  * <2->工作过程:
     * 解码过程: 将离散数字信号转换为离散模拟信号
     * 复现过程: 将离散的模拟信号转换为连续的模拟信号
**** 数字信号						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.7]
\begin{axis}[grid=both]
\addplot+[ycomb] plot coordinates
    {(0,2) (0.1,1) (0.3,1) (0.35,4) (0.5,3)
     (0.6,2) (0.7,2) (1,2)};
\end{axis}
\end{tikzpicture}
**** 复现:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.7]
\begin{axis}[grid=both]
\addplot+[const plot] plot coordinates
    {(0,2) (0.1,1) (0.3,1) (0.35,4) (0.5,3)
     (0.6,2) (0.7,2) (1,2)};
\end{axis}
\end{tikzpicture}

# *** 量化误差及其分析
*** 量化方法
 * <2->只舍不入: 只取量化单位  $q$  的整数部分
       \begin{eqnarray*}
	E(e) &=& \frac{q}{2} \\
	\sigma^2 &=& \frac{q^2}{3}
       \end{eqnarray*}
 * <3->有舍有入: 类似四舍五入
       \begin{eqnarray*}
	E(e) &=& 0 \\
	\sigma^2 &=& \frac{q^2}{12}
       \end{eqnarray*}
*** 减小量化误差方法
  * 减小  $q$  , 即增大字长  $i$  :   
         \[q=\frac{x_{max}-x_{min}}{2^i}\]
# *** 量化单位  $q$  对量化噪声的影响

** 离散系统研究方法
*** 离散系统研究方法
 *  连续系统: Laplacian 变换
 *  <2->离散系统: Z变换
 *  <3->离散系统学习要点
      * <4->离散数学模型
      * <5->离散系统的稳定性,稳态性能与动态性能分析
* 信号的采样与保持
\mode<article>{香农(Shannon)定理, 零阶保持器, 一阶保持器}
** 信号的采样
*** 采样信号
   *  <2->若采样开关为理想采样开关,则有:  
        \[e^*(t)=e(t)\delta_T(t)\]
      其中  $\delta_T(t)$  为理想单位脉冲序列:  
               \[\delta_T(t)=\sum_{n=0}^{\infty}\delta(t-nT)\]
   * <3->得:
      \begin{eqnarray*}
      e^{*}(t) & = & e(t)\sum_{n=0}^{\infty}\delta(t-nT) \\
        &=&  \sum_{n=0}^{\infty}e(t)\delta(t-nT) \\
        &=&  \sum_{n=0}^{\infty}e(nT)\delta(t-nT) 
      \end{eqnarray*}
***  采样信号的Laplacian变换
      \begin{eqnarray*}
      {\cal L}(e^{*}(t)) & =  & {\cal L}( \sum_{n=0}^{\infty}e(nT)\delta(t-nT) )\\
      &=&  \sum_{n=0}^{\infty}e(nT){\cal L}(\delta(t-nT) )\\
      &=&  \sum_{n=0}^{\infty}e(nT)e^{-nTs}
      \end{eqnarray*}
  *  <2->离散信号的Laplacian变换为  $s$  的超越函数,不易分析. 可利用Z变换分析.
*** 采样信号的频谱分析
 *  目的:分析  $e^*(t)$  与  $e(t)$  的关系,得到香农定理.
 *  <2->将  $\delta_T(t)$  以 Fourier 级数表示,得: 
      \begin{eqnarray*}
      \delta_T(t) & = &\sum_{n=-\infty}^{\infty}C_n e^{jn\omega_s t} \\
      C_n &=&\frac{1}{T}\int_{-\frac{T}{2}}^{\frac{T}{2}}\delta_T(t)e^{-jn\omega_s t}dt \\
        &=&\frac{1}{T}\int_{-\frac{T}{2}}^{\frac{T}{2}}\delta(t)dt \\ 
        &=& \frac{1}{T} \\
      \omega_s &=& \frac{1}{T} 
    \end{eqnarray*}
*** 采样信号的频谱分析(续)
  *  采样
      \begin{eqnarray*}
      \delta_T(t) &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}e^{jn\omega_s t} \\
      e^*(t) &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}e(t)e^{jn\omega_s t} \\
      E^*(s) &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}E(s+jn\omega_s ) \\
      E^*(j\omega) &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}E(j(\omega+n\omega_s)) 
      \end{eqnarray*}
 *  <2->$e^*(t)$  的频谱为以  $\omega_s$  为周期的无穷多个频谱之和.
 *  <3->设  $e(t)$ 带宽有限,最高角频率为  $\omega_h$ , 则当  $\omega_s>2\omega_h$  时,  $e^*(t)$  频谱的各部分不会相互重叠.
*** 香农定理
  * <2->若采样器的输入信号  $e(t)$ 只有有限带宽,且其最高频率分量为  $\omega_h$  ,
  * <3->当采样周期满足  
         \[T\leq\frac{2\pi}{2\omega_h}\]  
     则信号  $e(t)$  可以完全从  $e^*(t)$  中恢复出来.
*** 工程中  $T$  的选取
  *  <2->$T$  减小,失真度小,增加计算量
  *  <3->$T$  增大,动态性能差,稳定性难保证
  *  <4->经验方法:
        * <4->在随动系统中,若校正后系统截止频率为  $\omega_c$ ,则采样频率为  $\omega_s=10\omega_c$  , 即  $T=\frac{\pi}{5\omega_c}$
        * <5->按  $t_r,t_s$  选取,   $T=\frac{T_r}{10},T=\frac{t_s}{40}$
** 采样函数Laplacian变换性质
***  采样函数Laplacian变换性质:$G^*(s)=G^*(s+jk\omega_s)$
  * <2-> 证明:
      \begin{eqnarray*}
      G^*(s) &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}G(s+jn\omega_s) \\
      G^*(s+jk\omega_s) &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}G(s+j(n+k)\omega_s) \\
       &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}G(s+jn\omega_s)\\
       &=& G^*(s)
      \end{eqnarray*}
***  采样函数Laplacian变换性质:$[G(s)E^*(s)]^*=G^*(s)E^*(s)$
  * <2-> 证明
      \begin{eqnarray*}
      [G(s)E^*(s)]^* &= & \frac{1}{T}\sum_{n=-\infty}^{\infty}[G(s+jn\omega_s)E^*(s+jn\omega_s)] \\
       &=& \frac{1}{T}\sum_{n=-\infty}^{\infty}[G(s+jn\omega_s)E^*(s)] \\
       &=& (\frac{1}{T}\sum_{n=-\infty}^{\infty}G(s+jn\omega_s))E^*(s) \\
       &=& G^*(s)E^*(s)
      \end{eqnarray*}
** 信号的保持
*** 信号的保持
  * <2->将数字信号及脉冲信号转换成连续的模拟信号,采用保持器.主要解决  $nT$  与  $(n+1)T$  之间的插值问题.
  * <3->保持器是具有外推功能的元件,外推公式为:  
          \[e(nT+\Delta t)=a_0+a_1 \Delta t+a_2(\Delta t)^2+\cdots+a_m(\Delta t)^m\]
    式中  $a_0,\cdots,a_m$  由过去各采样时刻  $(m+1)$ 个离散的信号  $e^*((n-i)T),(i=0,\cdots,m)$  惟一确定.  
  * <4-> $m=0$ 时称为零阶保持器,  
  * <5-> $m=1$ 时称为一阶保持器.
*** 零阶保持器
  *  <2-> $e(nT+\Delta t)=a_0$  , 当  $\Delta t=0$  时,有  $e(nT)=a_0$ , 即按常值外推,  $e(t)=e(nT),t\in [ nT,(n+1)T)$ 
  *  <3-> 设零阶保持器输入为  $r^*(t)=\delta(t)$  ,则输出为  $e(t)=1,t\in [ nT,(n+1)T)$  因此
      \begin{eqnarray*}
      {\cal L} (r^*) &=& 1 \\
      {\cal L} (e) &=& \frac{1}{s}-\frac{e^{-Ts}}{s} \\
      G_h(s) &=& \frac{E(s)}{R^*(s)}
             = \frac{1-e^{-Ts}}{s} \\
      G_h(j\omega) &= &\frac{1-e^{-jT\omega}}{j\omega} 
       = \frac{e^{-j\omega T/2}(e^{j\omega T/2}-e^{-j\omega T/2})}{j\omega}\\
       &=& \frac{2\sin\frac{\omega T}{2}}{\omega}e^{-j\omega T/2} \\
       &=& \frac{2\sin\frac{\pi\omega}{\omega_s}}{\omega}e^{-j\pi\omega /\omega_s} 
      \end{eqnarray*}
*** 零阶保持器频率特性
**** Bode图						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.5]
%g=1-e^{-2\pi s}/s
\begin{axis}[
%axis x line=middle,axis y line= left, 
xticklabel=$\pgfmathprintnumber{\tick}\omega_s$ ,
yticklabel=$\pgfmathprintnumber{\tick}T$ ,
ylabel=$|G_h(j\omega)|$ ,xlabel=$\omega$ ,
every axis plot post/.append style={mark=none},
grid=both,
ymin=0,ymax=1.1,xmin=0.1,xmax=3]
\addplot[violet,thick] shell {octave -q --eval "w=[0.1:0.1:3]';m=abs(1/2/pi*(1-exp(-2*pi*j*w))./(j*w));disp([w,m]);" };
%\legend{$|G_h(j\omega)|$ , $\angle G_h(j\omega)$};
\end{axis}
\end{tikzpicture}

\begin{tikzpicture}[scale=0.5]
%g=1-e^{-2\pi s}/s
\begin{axis}[
%axis x line=middle,axis y line= left, 
xticklabel=$\pgfmathprintnumber{\tick}\omega_s$ ,
yticklabel=$\pgfmathprintnumber{\tick}\pi$ ,
ylabel=$\angle G_h(j\omega)$ ,xlabel=$\omega$ ,
every axis plot post/.append style={mark=none},
grid=both,
ymin=-3.5,ymax=0,xmin=0,xmax=3]
\addplot plot coordinates  {(0,0) (3,-3) };
\addplot plot coordinates  {(0,-1) (1,-1) (1,0)};
%\legend{$|G_h(j\omega)|$ , $\angle G_h(j\omega)$};
\end{axis}
\end{tikzpicture}

**** 零阶保持器特性					      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.3
     :BEAMER_env: block
     :BEAMER_envargs: <3->
     :END:
    * 低通
    * 相角迟后
    * 时间延迟
*** 一阶保持器
\begin{eqnarray*}
 e(nT+\Delta t) &=& a_0+a_1 \Delta t, \qquad (0\leq \Delta t < T) \\
 a_0& = & e(nT) \\
 a_1&=& \frac{e(nT)-e((n-1)T)}{T} \\
G_h(s) &=& T(1+s)\left(\frac{1-e^{-Ts}}{Ts}\right)^2 \\
G_h(j\omega) &=& \sqrt{1+(\omega T)^2}\left(\frac{2\sin\frac{\omega T}{2}}{\omega }\right)^2e^{-j(\omega T-\arctan\omega T)}
\end{eqnarray*}

  * <2-> 其相角迟后比零阶保持器大得多,大大降低了系统相位裕度  $\gamma$  ,
  * <3-> 因此一般只用零阶保持器.

