# +LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{etex}
#+LATEX_HEADER: \usepackage{amsmath}
 # +LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}
 # +LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}


#+startup: beamer
#+LaTeX_CLASS: beamer
# +LaTeX_CLASS_OPTIONS: [table]
# +LaTeX_CLASS_OPTIONS: [bigger]
 # +latex_header:  \usepackage{beamerarticle}
# +latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# +latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  线性系统的根轨迹法
#+latex_header: \subtitle{广义根轨迹与零度根轨迹}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:














* 广义根轨迹
** 广义根轨迹
变化参数可以是系统任意参数
*** 例:							      :B_block:BMCOL:
     :PROPERTIES:
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :BEAMER_col: 0.5
     :END:

$T_a$ 从 $0\rightarrow+\infty$ 时系统根轨迹.

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$r(t)$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
%\path[red] node[draw, right =of p1] (n) {$N$}; 
%\path[->] (p1) edge node[midway] {$x(t)$} (n) ; 
\path[red] node[draw, inner sep=5pt,right =of p1] (g) {$\frac{5}{s(5s+1)}$}; 
\path[->] (p1) edge node [midway]{$ $} (g); 
\path[->] node[ right =of g] (o) {$c(t)$}; 
\path[->] (g) edge node {} (o); 
\path[red] node[draw, inner sep=5pt,below =of g] (h) {$T_a s+1$}; 
\path[->,draw] (g.east)+(1em,0) |- (h.east); 
\path[->, draw] (h) -| node[very near end] {$-$} (p1); 
%\path[->, draw] (g.east)+(1em,0) -- +(1em,-3em) -| node[very near end] {$-$} (p1); 
\end{tikzpicture} 

解: 
\begin{eqnarray*}
G_o(s) &=&\frac{5(T_a s+1)}{s(5s+1)}\\
D(s) & = & 5s^2+(5T_a+1)s+5 \\
\end{eqnarray*}

*** 构造系统,						      :B_block:BMCOL:
     :PROPERTIES:
     :BEAMER_env: block
     :BEAMER_envargs: <3->
     :BEAMER_col: 0.5
     :END:

\[D(s)=5s^2+(5T_a+1)s+5\] 

等效开环传递函数: 

\[G'_o(s)=\frac{5T_a s}{5s^2+s+5}\]

求其 $180^\circ$ 根轨迹即可 .
** 广义根轨迹示例1
某负反馈系统开环传递函数为 $G_o(s)=\frac{K}{s(Ts+1)},K>0$  求 $T$ 从 $0\rightarrow+\infty$ 时闭环极点的运动轨迹,
并证明其根轨迹非实轴上的点构成一个圆,求出圆心和半径.
*** 解:							      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_envargs: <2->
     :BEAMER_env: block
     :END:
构造等效开环传递函数 $G_o'(s)$
\begin{eqnarray*}
D(s) &= & Ts^2+s+K \\
G_o'(s) &=&\frac{Ts^2}{s+K} \\
\end{eqnarray*}

*** 根轨迹图						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_envargs: <3->
     :BEAMER_env: block
     :END:

\begin{tikzpicture}
\coordinate (o) at (0,0);
\coordinate (ox) at (0.5,0);
\draw[->] (-3,0) -- (ox);
\draw[->] (0,-1.5) -- (0,1.5);
\draw (o) node[below left] {$o$};
\draw[thick,red] (-1,0) node {$\times$};
\draw[thick,red] (0,0) node {$o$};
%\draw [red,thick,smooth] plot coordinates {(-1,1) (-0.9,0.8) (-0.8,0.2) (-0.8,0) };
\draw [<->,red,thick] (0,0) arc (0:360:1);
\draw [->,red,thick] (-3,0)--(-2,0);
\draw [->,red,thick] (-1,0)--(-2,0);
\draw (-2,0) node[above left] {$-2K$};
\draw (-1,0) node[above ] {$-K$};
\end{tikzpicture}

** 广义根轨迹示例1(续)
*** 解法2:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_envargs: <2->
     :BEAMER_env: block
     :END:
\begin{eqnarray*}
Ts^2+s+K &=& 0 \\
s^2+\frac{1}{T}(s+K) &=& 0\\
G_o'(s) &=&\frac{K_g(s+K)}{s^2} \\
\frac{1}{T} &=& K_g
\end{eqnarray*}

*** 根轨迹图						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_envargs: <3->
     :BEAMER_env: block
     :END:
\begin{tikzpicture}
\coordinate (o) at (0,0);
\coordinate (ox) at (0.5,0);
\draw[->] (-3,0) -- (ox);
\draw[->] (0,-1.5) -- (0,1.5);
\draw (o) node[below left] {$o$};
\draw[thick,red] (0,0) node {$\times$};
\draw[thick,red] (-1,0) node {$o$};
%\draw [red,thick,smooth] plot coordinates {(-1,1) (-0.9,0.8) (-0.8,0.2) (-0.8,0) };
\draw [red,thick] (0,0) arc (0:360:1);
\draw [<->,red,thick] (-3,0)--(-1,0);
\draw (-2,0) node[above left] {$-2K$};
\draw (-1,0) node[above ] {$-K$};
\end{tikzpicture}

** 广义根轨迹示例1(续) 证明其非实轴上的根轨迹为圆:
 *  设根轨迹非实轴上的点为 $x+iy$, $D(s) = Ts^2+s+K=0$
       \begin{eqnarray*}
       T(x+iy)^2+x+iy+K &=& 0 \\
       T(x^2-y^2)+x+K+i(y+2xyT) &=& 0 \\
       Tx^2-Ty^2+x+K &=& 0 \\
       y+2xyT &=& 0 \\
       \end{eqnarray*}

** 广义根轨迹示例1(续) 圆心与半径:
 *  消去 $T$ 后,得:
       \begin{eqnarray*}
       \frac{-x}{2}+\frac{y^2}{2x}+x+K & = & 0 \\
       \frac{x}{2}+\frac{y^2}{2x}+K & = & 0 \\
       x^2+y^2+2xK & = & 0 \\
       (x+K)^2+y^2=K^2 
       \end{eqnarray*}
 * <2-> 圆心为 $(-K,0)$ ,半径为 $K$

* 零度根轨迹
** 零度根轨迹(正反馈系统)

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$r(t)$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
%\path[red] node[draw, right =of p1] (n) {$N$}; 
%\path[->] (p1) edge node[midway] {$x(t)$} (n) ; 
\path[red] node[draw, inner sep=5pt,right =of p1] (g) {$G(s)$}; 
\path[->] (p1) edge node [midway]{$ $} (g); 
\path[->] node[ right =of g] (o) {$c(t)$}; 
\path[->] (g) edge node {} (o); 
\path[red] node[draw, inner sep=5pt,below =of g] (h) {$H(s)$}; 
\path[->,draw] (g.east)+(1em,0) |- (h.east); 
\path[->, draw] (h) -| node[very near end] {$+$} (p1); 
%\path[->, draw] (g.east)+(1em,0) -- +(1em,-3em) -| node[very near end] {$-$} (p1); 
\end{tikzpicture} 

\begin{eqnarray*}
\Phi(s) &= &\frac{G(s)}{1-G(s)H(S)} \\
D(s) &=& 1-G(s)H(s) 
\end{eqnarray*}

  * <2->幅值条件: $|G(s)H(s)|=1$
  * <3->相角条件: $\angle G(s)H(s) =2k\pi$

** 根轨迹的起点,终点及分支数
  * 根轨迹起源于开环极点
  * 终止于开环零点
  * 有 $\max(m,n)$ 条分支数, 有n-m条趋向无穷远处.
** 根轨迹的对称性
    根轨迹对称于实轴
** 实轴上的根轨迹
    实轴上某区域若其右边开环实数零极点个数之和为偶数,则该区域为根轨迹区域.
** 渐近线
       * $\sigma_a =\frac{\sum_{i=1}^n p_i -\sum_{j=1}^m z_j}{n-m}$
       * $\phi = \frac{2k\pi}{n-m}$
** 分离点与分离角
    * 分离点: $M'(s)N(s)-M(s)N'(s)=0$
    * 分离角: $\theta_d=\frac{(2k+1)\pi}{l}, k=0,1,\cdots,l-1$, 其中 $l$ 为分离点处根轨迹的分支数
** 根轨迹的起始角与终止角
     \begin{eqnarray*}
     \theta_{p_i} & = & \frac{2k\pi}{I}+\frac{1}{I}\left[\sum_{j=1}^m\angle(p_i-z_j)-\sum_{\substack{j=1 \\ p_j\neq p_i}}^n\angle(p_i-p_j)\right] \\
     \phi_{z_j} & = & \frac{2k\pi}{J}-\frac{1}{J}\left[\sum_{\substack{i=1 \\ z_i\neq z_j}}^m\angle(z_j-z_i)-\sum_{i=1}^n\angle(z_j-p_i)\right] 
     \end{eqnarray*}
** 根轨迹与虚轴交点
    * 直接计算 将 $s=j\omega$ 代入 $D(s)$ ,求出 $K_g,\omega$ , $(0,j\omega)$ 即为交点
    * 利用Routh判据计算
** 根之和: $n-m\geq 2$ 时, 闭环极点之和等于开环极点之和
** 零度根轨迹示例1: 

某正反馈系统开环传递函数为 $G_o(s)=\frac{K_g(s+2)}{(s+3)(s^2+2s+2)}$

解:
  * <2->开环零点: $-2$, 开环极点: $-1\pm j, -3$
  * <3->分离点: $M'(s)N(s)-M(s)N'(s)=0$ 得: $s=-0.8$
  * <4->起始角: $\theta=\pm 71.6^\circ$

        \begin{tikzpicture}
        \coordinate (o) at (0,0);
        \coordinate (ox) at (0.5,0);
        \draw[->] (-3.5,0) -- (ox);
        \draw[->] (0,-1.5) -- (0,1.5);
        \draw (o) node[below left] {$o$};
        \draw[thick,red] (-3,0) node {$\times$};
        \draw[thick,red] (-1,1) node {$\times$};
        \draw[thick,red] (-1,-1) node {$\times$};
        \draw[thick,red] (-2,0) node {$o$};
        \draw [red,thick,smooth] plot coordinates {(-1,1) (-0.9,0.8) (-0.8,0.2) (-0.8,0) };
        \draw [red,thick,smooth] plot coordinates {(-1,-1) (-0.9,-0.8) (-0.8,-0.2) (-0.8,0) };
        \draw [->,red,thick] (-3,0)--(-3.5,0);
        \draw [<->,red,thick] (-2,0)--(0.5,0);
        \draw (-3,0) node[above ] {$-3$};
        \draw (-2,0) node[above ] {$-2$};
        \end{tikzpicture}

