# #+LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{etex}
#+LATEX_HEADER: \usepackage{amsmath}
 # +LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \pgfplotsset{compat=1.8}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
 # +LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}

#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [table]
# #+LaTeX_CLASS_OPTIONS: [bigger]
#+latex_header:  \mode<article>{\usepackage{beamerarticle}}
# #+latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# #+latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  非线性控制系统分析
#+latex_header: \subtitle{描述函数法}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:








* 基本概念
** 描述函数法基本概念
  * 1940年,P.J.Daniel提出,
  * 基本思想:
     在一定的假设条件下,将非线性环节在正弦信号作用下的输出用一次谐波分量近似,并导出非线性环节的等效近似频率特性,即描述函数.

** 描述函数法假设条件
\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$r(t)$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$   $ ,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[red] node[draw, right =of p1] (n) {$N$}; 
\path[->] (p1) edge node[midway] {$x(t)$} (n) ; 
\path[blue] node[draw, inner sep=5pt,right =of n] (g) {$G(s)$}; 
\path[->] (n) edge node [midway]{$y(t)$} (g); 
\path[->] node[ right =of g] (o) {$c(t)$}; 
\path[->] (g) edge node {} (o); 
\path[->, draw] (g.east)+(1em,0) -- +(1em,-3em) -| node[very near end] {$-$} (p1); 
\end{tikzpicture} 

  * 一个非线性环节N和一个线性部分串联
  * <2->非性环节是奇对称的:  $y(x)=-y(-x)$  即无恒定分量
  * <3-> $G(s)$ 具有较好的低通特性
** 描述函数定义
非线性环节输出信号的一次谐波分量和输入信号的复数比定义为非线性环节的描述函数.
\begin{eqnarray*}
x(t) & = & A\sin\omega t\\
y(t) &=& A_0+\sum_{n=1}^{\infty}(A_n\cos n\omega t + B_n\sin n\omega t)\\
A_n &=& \frac{1}{\pi}\int_0^{2\pi}y(t)\cos n\omega t d\omega t \\
A_n &=& \frac{1}{\pi}\int_0^{2\pi}y(t)\sin n\omega t d\omega t 
\end{eqnarray*}

分析:
  * <2-> $A_0=0$  ,(假设:奇对称性)
  * <3->n越大,谐波分量的频率越高,幅值  $A_n,B_n$  越小,(假设条件:G(s)具有较好的低通特性),高次谐波分量已被充分过滤掉
** 描述函数定义(续)
 * 非线性环节在  $x(t)=A\sin\omega t$  输入下
     \begin{align*}
      y(t) & \approx  y_1(t) = A_1\cos\omega t+B_1\sin\omega t   = Y_1\sin(\omega t+\phi_1) \\
       Y_1 &= \sqrt{A_1^2+B_1^2}  \qquad \phi_1 = \arctan\frac{A_1}{B_1} \\
     A_1 &= \frac{1}{\pi}\int_0^{2\pi}y(t)\cos \omega t d\omega t  \qquad B_1 = \frac{1}{\pi}\int_0^{2\pi}y(t)\sin \omega t d\omega t 
     \end{align*}
 * <2->描述函数为:
     \begin{align*}
     N(A) & = |N(A)|e^{j\angle N(A)} = \frac{Y_1}{A}e^{j\phi_1} \\
	  &= \frac{\sqrt{A_1^2+B_1^2}}{A}e^{j\arctan\frac{A_1}{B_1}} = \frac{B_1}{A}+j\frac{A_1}{A}
     \end{align*}
 * <3->若  $y(t)=-y(-t)$ ,则  $A_1=0,N(A)=\frac{B_1}{A}$ 
** 描述函数特点
 * <2->一般非线性环节的描述函数  $N$  为  $A$  及  $\omega$  的函数,表示成  $N(A,\omega)$  若非线性环节中不含储能元件,则只与  $A$  有关
 * <3->描述函数是非线性元件的等效传递特性,它是只考虑基波分量,忽略高次谐波分量之后的结果, 所以这种方法也称作谐波线性化法,当非线性元件用描述函数表示后,可以用频域法分析非线性系统的运动特性.
* 典型非线特性的描述函数
** 死区特性的描述函数
*** 死区特性						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.35
     :BEAMER_env: block
     :END:
\begin{tikzpicture}[scale=0.6]
%             /
%            /
%   ---------
%  /
% /
\coordinate (o) at (0,0);
\coordinate (ox) at (2.3,0);
\draw[->] (-2.3,0) -- (ox);
\draw[->] (0,-1.3) -- (0,1.3);
\draw (o) node[below left] {$o$};
\draw [blue,thick] plot coordinates {(-2,-1) (-1,0) (0,0) (1,0) (2,1)};
\draw (1,0) node[above] {$\Delta$};
\draw (-1,0) node[above ] {$-\Delta$};
\draw (1.5,0.5) node[above ] {$K$};
\end{tikzpicture}

*** 输入/输出信号					      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{tikzpicture}[scale=0.6]
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$   $ ,xlabel=$   $ ,
ymin=-1,ymax=1,xmin=-0,xmax=7,every axis plot post/.append style={mark=none}]
grid=both,
\addplot[blue,thick]
shell {
octave -q --eval "t=[0:0.1:2*pi]';disp([t,sin(t)]);"
};
\addplot[red,thick]
shell {
octave -q --eval "t=[0:0.1:2*pi]';x=sin(t);disp([t,max(x-0.5,0)+min(x+0.5,0)]);"
};
\legend{$\sin(t)$ , $y(sin(t))$};
\end{axis}
\end{tikzpicture}

** 死区特性的描述函数(续)
\begin{eqnarray*}
y(x) & = &\begin{cases} 
0  &  |x| \leq \Delta \\
K(x-\Delta)  & |x|>\Delta   \end{cases} \\
x &=& A\sin\omega t \\
y(t) &=& \begin{cases} 
0  &  0\leq \omega t \leq \psi_1 \\
K(A\sin\omega t-\Delta)  & \psi_1 < x \leq \frac{\pi}{2}   \end{cases} \\
\psi_1 &=& \arcsin\frac{\Delta}{A}
\end{eqnarray*}
 * <2-> 死区是奇对称的,  $A_1 = 0$
      \begin{eqnarray*}
      B_1 &=& \frac{1}{\pi}\int_0^{2\pi}y(t)\sin\omega t d\omega t 
           =  \frac{4}{\pi}\int_0^{\frac{\pi}{2}}K(A\sin\omega t -\Delta)\sin\omega t d\omega t \\
      N(A)&=&  \frac{B_1}{A} =\frac{2K}{\pi}\left(\frac{\pi}{2}-\arcsin\frac{\Delta}{A}-\frac{\Delta}{A}\sqrt{1-(\frac{\Delta}{A})^2}\right),\qquad A\geq\Delta
      \end{eqnarray*}
** 饱和特性的描述函数
*** 饱和特性							    :B_block:
     :PROPERTIES:
     :BEAMER_env: block
     :END:
\begin{tikzpicture}
%       ------
%      /
%------
\coordinate (o) at (0,0);
\coordinate (ox) at (2.3,0);
\draw[->] (-2.3,0) -- (ox);
\draw[->] (0,-1.3) -- (0,1.3);
\draw (o) node[below right] {$o$};
\draw [blue,thick] plot coordinates {(-2,-1) (-1,-1) (0,0) (1,1) (2,1)};
\draw (1,0) node[below] {$a$};
\draw (-1,0) node[below ] {$-a$};
\draw (0.5,0.5) node[above ] {$K$};
\end{tikzpicture}
*** 描述函数							    :B_block:
     :PROPERTIES:
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:

\begin{eqnarray*}
N(A) &=& \frac{B_1}{A} 
      =   \frac{2K}{\pi}\left(\arcsin\frac{a}{A}+\frac{a}{A}\sqrt{1-(\frac{a}{A})^2}\right) ,\qquad A\geq a 
\end{eqnarray*}
   * <3->当  $A\leq a$  时  $N(A)=K$ 
** 滞环特性的描述函数
*** 滞环特性						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :END:
\begin{tikzpicture}
%       /-/
%      / /
%     /-/
\coordinate (o) at (0,0);
\coordinate (ox) at (2.3,0);
\draw[->] (-2.3,0) -- (ox);
\draw[->] (0,-1.3) -- (0,1.3);
\draw (o) node[below right] {$o$};
\draw [blue,thick] plot coordinates {(-2,-1) (-1,0) (0,1) };
\draw [blue,thick] plot coordinates {(0,-1) (1,0) (2,1) };
\draw [red] plot coordinates {(0.3,-0.7) (1.7,0.7) (-0.3,0.7) (-1.7,-0.7) (0.3,-0.7) };
\draw [red,thick,->] (0.3,-0.7)-- (1,0);
\draw [red,thick,->] (1.7,0.7)--(0,0.7);
\draw [red,thick,->]  (-0.3,0.7)-- (-1,0) ;
\draw [red,thick,->]  (-1.7,-0.7)-- (0,-0.7) ;
\draw (1,0) node[below] {$b$};
\draw (-1,0) node[below ] {$-b$};
\draw (1.5,0.5) node[right ] {$K$};
\end{tikzpicture}
*** 描述函数						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
非单值奇对称  $A_1\neq 0,B_1\neq 0$ 
** 继电特性的描述函数
*** 继电特性						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :END:
\begin{tikzpicture}
%          --------
%          | |
%     -------- 
%     | |
%   -----
\coordinate (o) at (0,0);
\coordinate (ox) at (2.3,0);
\draw[->] (-2.3,0) -- (ox);
\draw[->] (0,-1.3) -- (0,1.3);
\draw (o) node[above left] {$o$};
\draw [red,thick] plot coordinates {(-2,-1) (-0.5,-1) };
\draw [red,thick] plot coordinates {(0.5,1) (2,1) };
\draw [red,thick] plot coordinates {(-1,0) (1,0) };
\draw [red,thick,->] (-1,0)-- (-1,-1);
\draw [red,thick,->]  (-0.5,-1)-- (-0.5,0) ;
\draw [red,thick,->] (0.5,1)--(0.5,0);
\draw [red,thick,->]  (1,0)-- (1,1) ;
\draw (1,0) node[below] {$h$};
\draw (0.5,0) node[below ] {$mh$};
\end{tikzpicture}

*** 描述函数						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
非单值奇对称     $N(A)=\frac{B_1}{A}+j\frac{A_1}{A}$ 
** 组合非线性特性的描述函数
  * 并联
     \begin{eqnarray*}
     y_1 & = & N_1(x)\\
     y_2 &=& N_2(x) \\
     y &=& y_1+y_2 \\
       &=& N_1(x)+N_2(x)
     \end{eqnarray*}
  * <2->串联:

     与联接次序有关

* 非线性系统稳定性分析
** 非线性系统稳定性分析
*** 线性系统有:						      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.45
    :BEAMER_env: block
    :END:
     \begin{eqnarray*}
     \Phi(s) &=& \frac{G(s)}{1+G(s)} \\
     1+G(s) &=& 0 \\
     G(s) &=& -1+j0 \\
     G(j\omega) &=& -1+j0
     \end{eqnarray*}
     Nyquist判据: 当  $G(j\omega)$ 曲线不包围 $(-1,j0)$ 点时,系统稳定,穿越 $(-1,j0)$ 时临界稳定
*** 非线性系统:						      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.55
    :BEAMER_env: block
    :BEAMER_envargs: <2->
    :END:
     \begin{eqnarray*}
     \Phi(j\omega) &=& \frac{N(A)G(j\omega)}{1+N(A)G(j\omega)} \\
     1+N(A)G(j\omega) &=& 0 \\
     G(s) &=& \frac{-1}{N(A)} 
     \end{eqnarray*}
    *  $\frac{-1}{N(A)}$ 称为负倒描述函数.
    * <3-> 推广Nyquist判据:若  $G(j\omega)$  曲线不包围  $\frac{-1}{N(A)}$ ,则稳定,包围  $\frac{-1}{N(A)}$  则不稳定.若相交,则非线性系统存在周期运动.
* 周期运动的稳定性
** 非线性系统的周期运动
 * 周期运动:用正弦的周期运动近似,频率和幅值可用交点处  $G(j\omega)$ 的对应  $\omega$  和  $\frac{-1}{N(A)}$  对应的  $A$  确定.
 * <2-> 稳定的周期运动: 非线性系统的自激振荡受干扰后能收敛于原来的等幅持续振荡.
** 周期运动稳定性分析,
*** Nyquist图						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :END:
\begin{tikzpicture}
\coordinate (o) at (0,0);
\coordinate (ox) at (0.5,0);
\draw[->] (-3.5,0) -- (ox);
\draw[->] (0,-3) -- (0,1);
\draw (o) node[below left] {$o$};
\draw [blue,smooth,thick] plot coordinates {(-3,-3) (-2.7,-2.5) (-2,-0.7) (-1,0.5) (0,0)};
\draw [red,smooth,thick] plot coordinates {(-3.5,-3) (-2.7,-2.5) (-2,-1.5) (-2,-0.7) (-3,-0.2)};
\draw[->,red,thick] (-3,-0.2)--(-3.1,-0.17);
\draw (-2,-0.7) node[right] {$M_1$};
\draw (-2.7,-2.5) node[above left] {$M_2$};
\end{tikzpicture}

*** $M_1,M_2$  均产生周期运动其中			      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :BEAMER_env: block
    :BEAMER_envargs: <2->
    :END:
 *  <2->$M_1$  点: 受扰动振幅  $A\uparrow$  ,不被Nyquist曲线包围,因此系统趋于稳定,导致振幅衰减, $A\downarrow$ ,又回到  $M_1$  点,因此  $M_1$  点处的周期运动  $A_1\sin\omega_1 t$  是稳定的
 *  <3->$M_2$  点: 受扰动振幅  $A\uparrow$  , 仍被Nyquist曲线包围,系统仍不稳定,导致振幅加剧, $A\uparrow$ ,进一步加剧振荡,最后会到达  $M_1$  点,因此  $M_2$  点处的周期运动是不稳定的

** 周期运动稳定性判别:
 *  $\frac{-1}{N(A)}$  由不稳定区域向稳定区域穿出时产生的周期运动是稳定的
 *  <2->$\frac{-1}{N(A)}$  由稳定区域向不稳定区域穿出时产生的周期运动是不稳定的
