<TeXmacs|2.1>

<style|<tuple|beamer|manila-paper>>

<\body>
  <screens|<\hidden>
    \;

    \;

    \;

    \;

    \;

    <doc-data|<doc-title|Introduction>>
  </hidden>|<\hidden>
    <tit|Example>

    Handwritten Digit Recognition

    <small-figure|<image|img/fig_1_1_digits.png|.7par|||>|Examples of
    hand-written digits taken from US zip codes.>
  </hidden>|<\hidden>
    <tit|Polynomial Curve Fitting>

    <small-figure|<image|img/fig_1_2_polynomial_curve_fitting.png|.45par|||>|<label|fig1.2>Plot
    of a training data set of <math|N=10> points, shown as blue circles, each
    comprising an observation of the input variable <math|x> along with the
    corresponding target variable <math|t>. The green curve shows the
    function <math|sin(2\<pi\>x)> used to generate the data. Our goal is to
    predict the value of <math|t> for some new value of <math|x>, without
    knowledge of the green curve.>
  </hidden>|<\hidden>
    Suppose that we are given a training set comprising <math|N> observations
    of <math|x>, written

    <\equation*>
      \<b-x\> \<equiv\> (x<rsub|1>,\<cdots\>,x<rsup|N>)<rsup|T>,
    </equation*>

    together with corresponding observations of the values \ of <math|t>,
    denoted\ 

    <\equation*>
      \<b-t\> \<equiv\> (t1, . . . , tN )T.
    </equation*>

    Figure <reference|fig1.2> shows a plot of a training set comprising<math|
    N=10> data points. The input data set <math|\<b-x\>> in Figure
    <reference|fig1.2> was generated by choosing values of <math|x<rsub|n>>,
    for <math|n = 1, . . . , N> , spaced uniformly in range <math|[0, 1]>,
    and the target data set <math|\<b-t\>> was obtained by first computing
    the corresponding values of the function <math|sin(2\<pi\>x)> and then
    adding a small level of random noise having a Gaussian distribution (the
    Gaussian distribution is discussed in Section 1.2.4) to each such point
    in order to obtain the corresponding value <math|t<rsub|n>>.
  </hidden>|<\hidden>
    \;

    \;

    consider a simple approach based on curve fitting. In particular, we
    shall fit the data using a polynomial function of the form

    <\equation*>
      y<around*|(|x,\<b-w\>|)>=w<rsub|0>+w<rsub|1>x+w<rsub|2>x<rsup|2>+\<cdots\>+w<rsub|M>x<rsup|M>=<big|sum><rsub|j=0><rsup|M>w<rsub|j>x<rsup|j>
    </equation*>

    where <math|M> is the order of the polynomial, and <math|x<rsub|j>>
    denotes <math|x> raised to the power of <math|j>.
  </hidden>|<\hidden>
    <\tit>
      Sum-of-Squares Error Function
    </tit>

    The values of the coefficients will be determined by fitting the
    polynomial to the training data.

    This can be done by minimizing an error function that measures the misfit
    between the function <math|y(x, \<b-w\>)>, for any given value of
    <math|\<b-w\>>, and the training set data points.\ 

    One simple choice of <em|error function>, which is widely used, is given
    by the sum of the squares of the errors between the predictions
    <math|y(x<rsub|n>,\<b-w\>)> for each data point <math|x<rsub|n>> and the
    corresponding target values <math|t<rsub|n>>, so that we minimize

    <\equation>
      E<around*|(|\<b-w\>|)>=<frac|1|2><big|sum><rsub|n=1><rsup|N><around*|{|y<around*|(|\<b-x\><rsub|n>,\<b-w\>|)>-t<rsub|n>|}><rsup|2><label|1.2>
    </equation>
  </hidden>|<\hidden>
    <small-figure|<image|img/fig_1_3_error_function.png|.5par|||>|The error
    function <eqref|1.2> corresponds to (one half of) the sum of the squares
    of the displacements (shown by the vertical green bars) of each data
    point from the function <math|y(x, w)>.>
  </hidden>|<\hidden>
    <tit|choosing the order <math|M> of the polynomial>

    There remains the problem of choosing the order <math|M> of the
    polynomial, and as we shall see this will turn out to be an example of an
    important concept called model <em|comparison or model selection>.\ 

    In Figure <reference|fig1.4>, we show four examples of the results of
    fitting polynomials having orders <math|M=0, 1, 3>, and 9 to the data set
    shown in Figure <reference|fig1.2>.
  </hidden>|<\hidden>
    <small-figure|<image|img/fig_1_4_plot_polynomials_M.png|.6par|||>|<label|fig1.4>Plots
    of polynomials having various orders <math|M> , shown as red curves,
    fitted to the data set shown in Figure <reference|fig1.2>.>
  </hidden>|<\hidden>
    <\tit>
      Over-fitting
    </tit>

    \;

    We notice that the constant (<math|M = 0>) and first order (<math|M = 1>)
    polynomials give rather poor fits to the data and consequently rather
    poor representations of the function <math|sin(2\<pi\>x)>.

    The third order (<math|M = 3>) polynomial seems to give the best fit to
    the function <math|sin(2\<pi\>x)> of the examples shown in Figure
    <reference|fig1.4>.

    When we go to a much higher order polynomial (<math|M = 9>), we obtain an
    excellent fit to the training data. In fact, the polynomial passes
    exactly through each data point and <math|E(w ) = 0>. However, the fitted
    curve oscillates wildly and gives a very poor representation of the
    function <math|sin(2\<pi\>x)>. This latter behaviour is known as
    <em|over-fitting>.
  </hidden>|<\hidden>
    As we have noted earlier, the goal is to achieve good generalization by
    making accurate predictions for new data.

    We can obtain some quantitative insight into the dependence of the
    generalization performance on <math|M> by considering a separate test set
    comprising 100 data points generated using exactly the same procedure
    used to generate the training set points but with new choices for the
    random noise values included in the target values.

    For each choice of <math|M> , we can then evaluate the residual value of
    <math|E(\<b-w\>)> given by <eqref|1.2> for the training data, and we can
    also evaluate <math|E(\<b-w\>)> for the test data set.\ 

    It is sometimes more convenient to use the root-mean-square (RMS) error
    defined by

    <\equation>
      E<rsub|RMS>=<sqrt|2E<around*|(|\<b-w\><rsup|\<ast\>>/N|)>><label|1.3>
    </equation>

    in which the division by <math|N> allows us to compare different sizes of
    data sets on an equal footing, and the square root ensures that ERMS is
    measured on the same scale (and in the same units) as the target variable
    <math|t>.
  </hidden>|<\hidden>
    <small-figure|<image|img/fig_1_5_E_RMS.png|.5par|||>|Graphs of the
    root-mean-square \ error, defined by <eqref|1.3>, evaluated on the
    training set and on an independent test set for various values of
    <math|M> .>
  </hidden>|<\hidden>
    <\tit>
      Polynomial Coefficients
    </tit>

    <small-table|<tabular|<tformat|<table|<row|<cell|<image|img/table_1_1_polynomial_coefficients.png|.5par|||>>>>>>|Table
    of the coefficients w for \ polynomials of various order. Observe how the
    typical magnitude of the coefficients increases dramatically as the order
    of the polynomial increases.>
  </hidden>|<\hidden>
    <tit|size of the data set>

    <small-figure|<image|img/fig_1_6_size_of_dataset.png|.9par|||>|Plots of
    the solutions obtained by minimizing the sum-of-squares error function
    using the <math|M = 9> polynomial for <math|N = 15> data points (left
    plot) and <math|N = 100> data points (right plot). We see that increasing
    the size of the data set reduces the over-fitting problem.>
  </hidden>|<\hidden>
    Also, there is something rather unsatisfying about having to limit the
    number of parameters in a model according to the size of the available
    training set.

    It would seem more reasonable to choose the complexity of the model
    according to the complexity of the problem being solved.

    We shall see that the least squares approach to finding the model
    parameters represents a specific case of <em|maximum likelihood>
    (discussed in Section 1.2.5), and that the over-fitting problem can be
    understood as a general property of maximum likelihood.

    By adopting a <em|Bayesian> approach, the \ over-fitting problem can be
    avoided. We shall see that there is no difficulty from a Bayesian
    perspective in employing models for which the number of parameters
    greatly exceeds the number of data points.

    Indeed, in a Bayesian model the <em|effective> number of parameters
    adapts automatically to the size of the data set.
  </hidden>|<\hidden>
    <\tit>
      Regularization
    </tit>

    For the moment, however, it is instructive to continue with the current
    approach and to consider how in practice we can apply it to data sets of
    limited size where we may wish to use relatively complex and flexible
    models.

    One technique that is often used to control the over-fitting phenomenon
    in such cases is that of <em|regularization>, which involves adding a
    penalty term to the error function <eqref|1.2> in order to discourage the
    coefficients from reaching large values.
  </hidden>|<\hidden>
    The simplest such penalty term takes the form of a sum of squares of all
    of the coefficients, leading to a modified error function of the form

    <\equation>
      <wide|E|~><around*|(|\<b-w\>|)>=<frac|1|2><big|sum><rsub|n=1><rsup|N><around*|{|y<around*|(|x<rsub|n>,\<b-w\>|)>-t<rsub|n>|}><rsup|2>+<with|color|red|<frac|\<lambda\>|2><around*|\<\|\|\>|\<b-w\>|\<\|\|\>><rsup|2>><label|1.4>
    </equation>

    where <math|\<\|\|\>\<b-w\>\<\|\|\><rsup|2>\<equiv\>\<b-w\><rsup|T>\<b-w\>=w<rsub|0><rsup|2>+w<rsub|1><rsup|2>+
    \<cdots\>+w<rsup|2><rsub|M>>, and the coefficient <math|\<lambda\>>
    governs the relative importance of the regularization term compared with
    the sum-of-squares error term.

    Note that often the coefficient <math|w<rsub|0>> is omitted from the
    regularizer because its inclusion causes the results to depend on the
    choice of origin for the target variable (Hastie et al., 2001), or it may
    be included but with its own regularization coefficient (we shall discuss
    this topic in more detail in Section 5.5.1).\ 

    Again, the error function in <eqref|1.4> can be minimized exactly in
    closed form. Techniques such as this are known in the statistics
    literature as <em|shrinkage> methods because they reduce the value of the
    coefficients. The particular case of a quadratic regularizer is called
    <em|ridge regression> (Hoerl and Kennard, 1970). In the context of neural
    networks, this approach is known as weight decay.
  </hidden>|<\hidden>
    <small-figure|<image|img/fig_1_7_regularization.png|.9par|||>|<label|fig1.7>Plots
    of <math|M=9> polynomials fitted to the data set shown in Figure
    <reference|fig1.2> using the regularized error function <eqref|1.4> for
    two values of the regularization parameter <math|\<lambda\>>
    corresponding to <math|ln \<lambda\> = \<minus\>18> and <math|ln
    \<lambda\> = 0>. The case of no regularizer, i.e., <math|\<lambda\> = 0>,
    corresponding to <math|ln \<lambda\> = \<minus\>\<infty\>>, is shown at
    the bottom right of Figure <reference|fig1.4>.>
  </hidden>|<\hidden>
    <small-table|<tabular|<tformat|<table|<row|<cell|<image|img/table_1_2_coefficients_regularized.png|.5par|||>>>>>>|Table
    of the coefficients <math|\<b-w\><rsup|\<ast\>>> for <math|M = \ 9>
    polynomials with various values for the regularization parameter
    <math|\<lambda\>>. Note that ln <math|\<lambda\> = \<minus\>\<infty\>>
    corresponds to a model with no regularization, i.e., to the graph at the
    bottom right in Figure <reference|fig1.4>. We see that, as the value of
    <math|\<lambda\>> increases, the typical magnitude of the coefficients
    gets smaller.>
  </hidden>|<\hidden>
    \;

    <small-figure|<image|img/fig_1_8_train_test_error_M9.png|.5par|||>|Graph
    of the root-mean-square error <eqref|1.3> versus <math|ln \<lambda\>> for
    the <math|M = 9> polynomial.>
  </hidden>|<\hidden>
    <tit|Probability Theory>

    <small-figure|<image|img/fig_1_9_apple_orange.png|.5par|||>|We use a
    simple example of two coloured boxes each containing fruit (apples shown
    in green and oranges shown in orange) to introduce the basic ideas of
    probability.>
  </hidden>|<\hidden>
    \;

    <small-figure|<image|img/fig_1_10_two_random_variables.png|.4par|||>|<label|fig1.10>We
    can derive the sum and product rules of probability by considering two
    random variables, <math|X>, which takes the values <math|{x<rsub|i>}>
    where <math|i=1,\<cdots\>,M>, and <math|Y>, which takes the values
    <math|{y<rsub|j>}> where <math|j=1,\<cdots\>,L>. In this illustration we
    have <math|M = 5> and<math| L = 3>. If we consider a total number
    <math|N> of instances of these variables, then we denote the number of
    instances where <math|X = x<rsub|i>> and <math|Y = y<rsub|j>> by
    <math|n<rsub|i j>>, which is the number of points in the corresponding
    cell of the array. The number of points in column <math|i>, corresponding
    to <math|X = x<rsub|i>>, is denoted by <math|c<rsub|i>>, and the number
    of points in row <math|j>, corresponding to <math|Y = y<rsub|j>>, is
    denoted by <math|r<rsub|j>>.>
  </hidden>|<\hidden>
    The probability that <math|X> will take the value <math|x<rsub|i>> and
    <math|Y> will take the value <math|y<rsub|j>> is written <math|p(X =
    x<rsub|i>, Y = y<rsub|j>)> and is called the <em|joint> probability of
    <math|X = x<rsub|i>> and <math|Y = y<rsub|j>>. It is given by the number
    of points falling in the cell <math|i,j> as a fraction of the total
    number of points, and hence

    <\equation>
      p<around*|(|X=x<rsub|i>,Y=y<rsub|j>|)>=<frac|n<rsub|i j>|N><label|1.5>
    </equation>

    Here we are implicitly considering the limit <math|N \<rightarrow\>
    \<infty\>>. Similarly, the probability that <math|X> takes the value
    <math|x<rsub|i>> irrespective of the value of <math|Y> is written as
    <math|p(X = x<rsub|i>)> and is given by the fraction of the total number
    of points that fall in column <math|i>, so that

    <\equation>
      p(X = x<rsub|i>) = <frac|c<rsub|i>|N> .<label|1.6>
    </equation>
  </hidden>|<\hidden>
    Because the number of instances in column i in Figure <reference|fig1.10>
    is just the sum of the number of instances in each cell of that column,
    we have <math|c<rsub|i> = <big|sum><rsub|j>n<rsub|i j>> and therefore,
    from Eq. <eqref|1.5> and <eqref|1.6>, we have

    <\equation*>
      p<around*|(|X=x<rsub|i>|)>=<big|sum><rsub|j=1><rsup|L>p<around*|(|X=x<rsub|i>,Y=y<rsub|j>|)>
    </equation*>

    which is the<em| sum rule> of probability.

    Note that <math|p(X = x<rsub|i>)> is sometimes called the <em|marginal>
    probability, because it is obtained by marginalizing, or summing out, the
    other variables (in this case <math|Y>).
  </hidden>|<\hidden>
    If we consider only those instances for which <math|X = x<rsub|i>>, then
    the fraction of such instances for which <math|Y = y<rsub|j>> is written
    <math|p(Y = y<rsub|j>\|X = x<rsub|i>)> and is called the <em|conditional
    probability> of <math|Y = y<rsub|j>> given <math|X = x<rsub|i>>. It is
    obtained by finding the fraction of those points in column <math|i> that
    fall in cell <math|i,j> and hence is given by

    <\equation>
      p<around*|(|Y=y<rsub|j>\|X=x<rsub|i>|)>=<frac|n<rsub|i
      j>|c<rsub|i>>.<label|1.8>
    </equation>

    From Eq. <eqref|1.5>, <eqref|1.6>, and <eqref|1.8>, we can then derive
    the following relationship

    <\eqnarray*>
      <tformat|<table|<row|<cell|p<around*|(|X=x<rsub|i>,Y=y<rsub|j>|)>>|<cell|=>|<cell|<frac|n<rsub|i
      j>|N>>>|<row|<cell|>|<cell|=>|<cell|<frac|n<rsub|i
      j>|c<rsub|i>>.<frac|c<rsub|i>|N>>>|<row|<cell|>|<cell|=>|<cell|p<around*|(|Y=y<rsub|j>\|X=x<rsub|i>|)>p<around*|(|X=x<rsub|i>|)>>>>>
    </eqnarray*>

    which is the <em|product rule> of probability.
  </hidden>|<\hidden>
    <tit|The Rules of Probability>

    sum rule

    <\equation*>
      p<around*|(|X|)>=<big|sum><rsub|Y>p<around*|(|X,Y|)>
    </equation*>

    product rule

    <\equation*>
      p<around*|(|X,Y|)>=p<around*|(|Y\|X|)>p<around*|(|X|)>
    </equation*>
  </hidden>|<\hidden>
    <tit|Bayes' Theorem>

    From the product rule, together with the symmetry property <math|p(X, Y )
    = p(Y, X)>, we immediately obtain the following relationship between
    conditional probabilities

    <\equation*>
      p<around*|(|Y\|X|)>=<frac|p<around*|(|X\|Y|)>p<around*|(|Y|)>|p<around*|(|X|)>>
    </equation*>

    which is called<em| Bayes' theorem> and plays a central role in pattern
    recognition and machine learning.\ 

    <\equation*>
      posterior\<propto\>likelihood\<times\>prior
    </equation*>

    \;
  </hidden>|<\hidden>
    \;

    Using the sum rule, the denominator in Bayes' theorem can be expressed in
    terms of the quantities appearing in the numerator

    <\equation*>
      p<around*|(|X|)>=<big|sum><rsub|Y>p<around*|(|X\|Y|)>p<around*|(|Y|)>
    </equation*>

    which is called Bayes' theorem and which plays a central role in pattern
    recognition and machine learning. Using the sum rule, the denominator in
    Bayes' theorem can be expressed in terms of the quantities appearing in
    the numerator
  </hidden>|<\hidden>
    <tit|illustration of a distribution>

    <small-figure|<image|img/fig_1_11_illustration_of_distribution.png|.45par|||>|An
    illustration of a distribution over two variables, <math|X>, which takes
    <math|9> possible values, and <math|Y>, which takes two possible values.
    The top left figure shows a sample of 60 points drawn from a joint
    probability distribution over these variables. The remaining figures show
    histogram estimates of the marginal distributions <math|p(X)> and
    <math|p(Y)>, as well as the conditional distribution <math|p(X\|Y = 1)>
    corresponding to the bottom row in the lower right.>
  </hidden>|<\hidden>
    <tit|Probability Densities>

    <small-figure|<image|img/fig_1_12_probability_density.png|.45par|||>|The
    concept of probability for \ discrete variables can be extended to that
    of a probability density <math|p(x)> over a continuous variable <math|x>
    and is such that the probability of <math|x> lying in the interval
    <math|(x, x + \<delta\>x)> is given by <math|p(x)\<delta\>x> for
    <math|\<delta\>x \<rightarrow\> 0>. The probability density can be
    expressed as the derivative of a cumulative distribution function
    <math|P(x)>.>
  </hidden>|<\hidden>
    The probability that <math|x> will lie in an interval <math|(a, b)> is
    then given by

    <\equation*>
      p<around*|(|x\<in\><around*|(|a,b|)>|)>=<big|int><rsub|a><rsup|b>p<around*|(|x|)>\<mathd\>x
    </equation*>

    Because probabilities are nonnegative, and because the value of <math|x>
    must lie somewhere on the real axis, the probability density <math|p(x)>
    must satisfy the two conditions

    <\eqnarray*>
      <tformat|<table|<row|<cell|p<around*|(|x|)>>|<cell|\<geqslant\>>|<cell|0>>|<row|<cell|<big|int><rsub|-\<infty\>><rsup|\<infty\>>p<around*|(|x|)>\<mathd\><around*|(|x|)>>|<cell|=>|<cell|1>>>>
    </eqnarray*>

    The probability that x lies in the interval <math|(\<minus\>\<infty\>,
    z)> is given by the cumulative distribution function defined by

    <\equation*>
      P<around*|(|z|)>=<big|int><rsub|-\<infty\>><rsup|z>p<around*|(|x|)>\<mathd\>x
    </equation*>
  </hidden>|<\hidden>
    <tit|Transformed Densities>

    <image|img/slide_distribution_transform.png|1par|||>
  </hidden>|<\hidden>
    <tit|multivariate probability density>

    If we have several continuous variables
    <math|x<rsub|1>,\<cdots\>,x<rsub|D>>, denoted collectively by the vector
    <math|\<b-x\>>, then we can define a joint probability density

    <\equation*>
      p(\<b-x\>) = p(x<rsub|1>,\<cdots\>,x<rsub|D>)
    </equation*>

    such that the probability of <math|x> falling in an infinitesimal volume
    <math|\<delta\>\<b-x\>> containing the point <math|\<b-x\>> is given by
    <math|p(\<b-x\>)\<delta\>\<b-x\>>. This multivariate probability density
    must satisfy

    <\eqnarray*>
      <tformat|<table|<row|<cell|p<around*|(|\<b-x\>|)>>|<cell|\<geqslant\>>|<cell|0>>|<row|<cell|<big|int>p<around*|(|\<b-x\>|)>\<mathd\>\<b-x\>>|<cell|=>|<cell|1>>>>
    </eqnarray*>

    in which the integral is taken over the whole of x space.\ 
  </hidden>|<\hidden>
    \;

    \;

    We can also consider joint probability distributions over a combination
    of discrete and continuous variables.

    Note that if <math|\<b-x\>> is a discrete variable, then
    <math|p(\<b-x\>)> is sometimes called a <em|probability mass function>
    because it can be regarded as a set of `probability masses' concentrated
    at the allowed values of <math|\<b-x\>>.
  </hidden>|<\hidden>
    <tit|sum and product rules>

    The sum and product rules of probability, as well as Bayes' theorem,
    apply equally to the case of probability densities, or to combinations of
    discrete and continuous variables.For instance, if <math|x> and <math|y>
    are two real variables, then the sum and product rules take the form

    <\eqnarray*>
      <tformat|<table|<row|<cell|p<around*|(|x|)>>|<cell|=>|<cell|<big|int>p<around*|(|x,y|)>\<mathd\>y>>|<row|<cell|p<around*|(|x,y|)>>|<cell|=>|<cell|p<around*|(|y\|x|)>p<around*|(|x|)>>>>>
    </eqnarray*>

    A formal justification of the sum and product rules for continuous
    variables (Feller, 1966) requires a branch of mathematics called measure
    theory and lies outside the scope of this book.

    Its validity can be seen informally, however, by dividing each real
    variable into intervals of width <math|\<#2206\>> and considering the
    discrete probability distribution over these intervals.

    Taking the limit <math|\<#2206\> \<rightarrow\> 0> then turns sums into
    integrals and gives the desired result.
  </hidden>|<\hidden>
    <tit|Expectations>

    One of the most important operations involving probabilities is that of
    finding weighted averages of functions. The average value of some
    function <math|f(x)> under a probability distribution <math|p(x)> is
    called the expectation of <math|f(x)> and will be denoted by <math|E[f]>.

    For a discrete distribution, it is given by

    <\equation*>
      \<bbb-E\><around*|[|f|]>=<big|sum><rsub|x>p<around*|(|x|)>f<around*|(|x|)>
    </equation*>

    so that the average is weighted by the relative probabilities of the
    different values of <math|x>.\ 

    In the case of continuous variables, expectations are expressed in terms
    of an integration with respect to the corresponding probability density

    <\equation*>
      \<bbb-E\><around*|[|f|]>=<big|int>p<around*|(|x|)>f<around*|(|x|)>\<mathd\>x
    </equation*>

    \;
  </hidden>|<\hidden>
    \;

    \;

    In either case, if we are given a finite number N of points drawn from
    the probability distribution or probability density, then the expectation
    can be approximated as a finite sum over these points

    <\equation*>
      \<bbb-E\><around*|[|f|]>\<simeq\><frac|1|N><big|sum><rsub|n=1><rsup|N>f<around*|(|x<rsub|n>|)>.
    </equation*>

    The approximation becomes exact in the limit <math|N \<rightarrow\>
    \<infty\>>.

    \;

    \;
  </hidden>|<\hidden>
    Sometimes we will be considering expectations of functions of several
    variables, in which case we can use a subscript to indicate which
    variable is being averaged over, so that for instance

    <\equation*>
      \<bbb-E\><rsub|x>[f (x, y)]
    </equation*>

    denotes the average of the function <math|f (x, y)> with respect to the
    distribution of <math|x>. Note that <math|\<bbb-E\><rsub|x>[f (x, y)]>
    will be a function of <math|y>. \ 

    We can also consider a conditional expectation with respect to a
    conditional distribution, so that

    <\equation*>
      \<bbb-E\><rsub|x>[f \|y] = <big|sum><rsub|x>p(x\|y)f (x)
    </equation*>

    with an analogous definition for continuous variables.
  </hidden>|<\hidden>
    <tit|Variance>

    The <em|variance> of <math|f(x)> is defined by

    <\equation*>
      var[f ] = \<bbb-E\> [(f (x) \<minus\> \<bbb-E\>[f (x)])<rsup|2>]
    </equation*>

    and provides a measure of how much variability there is in <math|f(x)>
    around its mean value <math|\<bbb-E\>[f(x)]>. Expanding out the square,
    we see that the variance can also be written in terms of the expectations
    of <math|f(x>) and <math|f (x)<rsup|2>>

    <\equation*>
      var[f ] = \<bbb-E\>[f (x)<rsup|2>] \<minus\> <around*|(|\<bbb-E\>[f
      (x)]|)><rsup|2>
    </equation*>

    In particular, we can consider the variance of the variable <math|x>
    itself, which is given by

    <\equation*>
      var[x] = \<bbb-E\>[x<rsup|2>]\<minus\><around*|(|\<bbb-E\>[x]|)><rsup|2>
    </equation*>
  </hidden>|<\hidden>
    For two random variables <math|x> and <math|y>, the covariance is defined
    by

    <\eqnarray*>
      <tformat|<table|<row|<cell|cov[x, y]
      >|<cell|=>|<cell|\<bbb-E\><rsub|x,y>[{x \<minus\> \<bbb-E\>[x]} {y
      \<minus\> \<bbb-E\>[y]}]>>|<row|<cell|>|<cell|=>|<cell|\<bbb-E\><rsub|x,y>[x
      y] \<minus\> \<bbb-E\>[x]\<bbb-E\>[y]>>>>
    </eqnarray*>

    which expresses the extent to which <math|x> and <math|y> vary together.
    If <math|x> and <math|y> are independent, then their covariance vanishes.

    In the case of two vectors of random variables <math|\<b-x\>> and
    <math|\<b-y\>>, the covariance is a matrix \ 

    <\eqnarray*>
      <tformat|<table|<row|<cell|cov[x, y]
      \ >|<cell|=>|<cell|\<bbb-E\><rsub|x,y>[{\<b-x\>\<minus\>\<bbb-E\>[\<b-x\>]}{\<b-y\><rsup|T>\<minus\>\<bbb-E\>[\<b-y\><rsup|T>]}]
      >>|<row|<cell|>|<cell|=>|<cell|\<bbb-E\><rsub|x,y>[\<b-x\>\<b-y\><rsup|T>]
      \<minus\> E[\<b-x\>]E[\<b-y\><rsup|T>]>>>>
    </eqnarray*>

    If we consider the covariance of the components of a vector
    <math|\<b-x\>> with each other, then we use a slightly simpler notation
    <math|cov[\<b-x\>]\<equiv\>cov[\<b-x\>,\<b-x\>]>.
  </hidden>|<\hidden>
    <tit|Bayesian probabilities>

    So far in this chapter, we have viewed probabilities in terms of the
    frequencies of random, repeatable events. We shall refer to this as the
    classical or <em|frequentist> interpretation of probability.\ 

    Now we turn to the more general <em|Bayesian> view, in which
    probabilities provide a quantification of uncertainty.

    The use of probability to represent uncertainty, however, is not an
    ad-hoc choice, but is inevitable if we are to respect common sense while
    making rational coherent inferences.

    \;
  </hidden>|<\hidden>
    <tit|Bayesian perspective>

    \;

    In the field of pattern recognition, too, it is helpful to have a more
    general notion of probability. Consider the example of polynomial curve
    fitting discussed in Section 1.1.\ 

    It seems reasonable to apply the frequentist notion of probability to the
    random values of the observed variables <math|t<rsub|n>>.\ 

    However, we would like to address and quantify the uncertainty that
    surrounds the appropriate choice for the model parameters <math|\<b-w\>>.

    We shall see that, from a Bayesian perspective, we can use the machinery
    of probability theory to describe the uncertainty in model parameters
    such as <strong|<math|\<b-w\>>>, or indeed in the choice of model itself.
  </hidden>|<\hidden>
    <tit|Bayes' theorem>

    \;

    \;

    Bayes' theorem now acquires a new significance. Recall that in the boxes
    of fruit example, the observation of the identity of the fruit provided
    relevant information that altered the probability that the chosen box was
    the red one.

    In that example, Bayes' theorem was used to convert a prior probability
    into a posterior probability by incorporating the evidence provided by
    the observed data.

    As we shall see in detail later, we can adopt a similar approach when
    making inferences about quantities such as the parameters <math|\<b-w\>>
    in the polynomial curve fitting example.

    \;
  </hidden>|<\hidden>
    We capture our assumptions about <strong|<math|\<b-w\>>>, before
    observing the data, in the form of a prior probability distribution
    <math|p(\<b-w\>)>.\ 

    The effect of the observed data <math|\<cal-D\> =
    {t<rsub|1>,\<cdots\>,t<rsub|N>}> is expressed through the conditional
    probability <math|p(\<cal-D\>\|\<b-w\>)>, and we shall see later, in
    Section 1.2.5, how this can be represented explicitly. Bayes' theorem,
    which takes the form

    <\equation>
      p<around*|(|\<b-w\>\|\<cal-D\>|)>=<frac|p<around*|(|\<cal-D\>\|\<b-w\>|)>p<around*|(|\<b-w\>|)>|p<around*|(|\<cal-D\>|)>><label|1.43>
    </equation>

    then allows us to evaluate the uncertainty in w after we have observed
    <math|\<cal-D\>> in the form of the posterior probability
    <math|p(\<b-w\>\|\<cal-D\>)>.
  </hidden>|<\hidden>
    <tit|<em|likelihood function>>

    The quantity <math|p(\<cal-D\>\|\<b-w\>)> on the right-hand side of
    Bayes' theorem is evaluated for the observed data set <math|\<cal-D\>>
    and can be viewed as a function of the parameter vector <math|\<b-w\>>,
    in which case it is called the <em|likelihood function>.\ 

    It expresses how probable the observed data set is for different settings
    of the parameter vector <math|\<b-w\>>. Note that the likelihood is not a
    probability distribution over <math|\<b-w\>>, and its integral with
    respect to <math|\<b-w\>> does not (necessarily) equal one.

    Given this definition of likelihood, we can state Bayes' theorem in words

    <\equation*>
      posterior \<propto\> likelihood \<times\> prior
    </equation*>

    where all of these quantities are viewed as functions of <math|\<b-w\>>.

    \;
  </hidden>|<\hidden>
    \;

    \;

    \;

    The denominator in Eq. <eqref|1.43> is the normalization constant, which
    ensures that the posterior distribution on the left-hand side is a valid
    probability density and integrates to one.\ 

    Indeed, integrating both sides of Eq. <eqref|1.43> with respect to
    <math|\<b-w\>>, we can express the denominator in Bayes' theorem in terms
    of the prior distribution and the likelihood function

    <\equation*>
      p(\<cal-D\>) = \ <big|int> p(\<cal-D\>\|\<b-w\>)p(\<b-w\>)
      \<mathd\>\<b-w\>.
    </equation*>
  </hidden>|<\hidden>
    \;

    In both the Bayesian and frequentist paradigms, the likelihood function
    <math|p(\<cal-D\>\|\<b-w\>)> plays a central role. However, the manner in
    which it is used is fundamentally different in the two approaches.\ 

    In a frequentist setting, <math|\<b-w\>> is considered to be a fixed
    parameter, whose value is determined by some form of `estimator', and
    error bars on this estimate are obtained by considering the distribution
    of possible data sets <math|\<cal-D\>>.

    By contrast, from the Bayesian viewpoint there is only a single data set
    <math|\<cal-D\>> (namely the one that is actually observed), and the
    uncertainty in the parameters is expressed through a probability
    distribution over <math|\<b-w\>>.
  </hidden>|<\hidden>
    <tit| <em|maximum likelihood>>

    \;

    A widely used frequentist estimator is <em|maximum likelihood>, in which
    <math|\<b-w\>> is set to the value that maximizes the likelihood function
    <math|p(\<cal-D\>\|\<b-w\>)>.

    This corresponds to choosing the value of <math|\<b-w\>> for which the
    probability of the observed data set is maximized.

    In the machine learning literature, the negative log of the likelihood
    function is called an <em|error function>. Because the negative logarithm
    is a monotonically decreasing function, maximizing the likelihood is
    equivalent to minimizing the error.
  </hidden>|<\hidden>
    <tit|bootstrap>

    One approach to determining frequentist error bars is the <em|bootstrap>
    (Efron, 1979; Hastie et al., 2001), in which multiple data sets are
    created as follows.

    Suppose our original data set consists of <math|N> data points <math|X =
    {x<rsub|1>,\<cdots\>, x<rsub|N>}>. We can create a new data set
    <math|X<rsub|B>> by drawing <math|N> points at random from <math|X>, with
    replacement, so that some points in <math|X> may be replicated in
    <math|X<rsub|B>>, whereas other points in <math|X> may be absent from
    <math|X<rsub|B>>.

    This process can be repeated <math|L> times to generate <math|L> data
    sets each of size <math|N> and each obtained by sampling from the
    original data set <math|X>.\ 

    The statistical accuracy of parameter estimates can then be evaluated by
    looking at the variability of predictions between the different bootstrap
    data sets.
  </hidden>|<\hidden>
    <tit|One advantage of the Bayesian viewpoint>

    One advantage of the Bayesian viewpoint is that the inclusion of prior
    knowledge arises naturally.\ 

    Suppose, for instance, that a fair-looking coin is tossed three times and
    lands heads each time. A classical maximum likelihood estimate of the
    probability of landing heads would give 1, implying that all future
    tosses will land heads!

    By contrast, a Bayesian approach with any reasonable prior will lead to a
    much less extreme conclusion.
  </hidden>|<\hidden>
    <tit|controversy and debate>

    There has been much controversy and debate associated with the relative
    merits of the frequentist and Bayesian paradigms, which have not been
    helped by the fact that there is no unique frequentist, or even Bayesian,
    viewpoint.

    For instance, one common criticism of the Bayesian approach is that the
    prior distribution is often selected on the basis of mathematical
    convenience rather than as a reflection of any prior beliefs.

    Even the subjective nature of the conclusions through their dependence on
    the choice of prior is seen by some as a source of difficulty.

    Reducing the dependence on the prior is one motivation for so-called
    <em|noninformative> priors. \ However, these lead to difficulties when
    comparing different models, and indeed Bayesian methods based on poor
    choices of prior can give poor results with high confidence.

    Frequentist evaluation methods offer some protection from such problems,
    and techniques such as cross-validation remain useful in areas such as
    model \ comparison.
  </hidden>|<\shown>
    <tit|The Gaussian distribution>

    <small-figure|<image|img/fig_1_13_gaussian.png|.5par|||>|Plot of the
    univariate Gaussian \ showing the mean <math|\<mu\>> and the standard
    deviation <math|\<sigma\>>.>
  </shown>|<\hidden>
    <\tit>
      Gaussian Mean and Variance
    </tit>

    <\eqnarray*>
      <tformat|<table|<row|<cell|\<cal-N\><around*|(|x\|\<mu\>,\<sigma\><rsup|2>|)>>|<cell|=>|<cell|<frac|1|<around*|(|2\<pi\>\<sigma\><rsup|2>|)><rsup|1/2>>exp<around*|{|-<frac|1|2\<sigma\><rsup|2>><around*|(|x-\<mu\>|)><rsup|2>|}>>>|<row|<cell|\<cal-N\><around*|(|x\|\<mu\>,\<sigma\><rsup|2>|)>>|<cell|\<gtr\>>|<cell|0>>|<row|<cell|<big|int><rsub|-\<infty\>><rsup|\<infty\>>\<cal-N\><around*|(|x\|\<mu\>,\<sigma\><rsup|2>|)>\<mathd\>x>|<cell|=>|<cell|1>>|<row|<cell|\<bbb-E\><around*|[|x|]>>|<cell|=>|<cell|<big|int><rsub|-\<infty\>><rsup|\<infty\>>\<cal-N\><around*|(|x\|\<mu\>,\<sigma\><rsup|2>|)>x\<mathd\>x=\<mu\>>>|<row|<cell|\<bbb-E\><around*|[|x<rsup|2>|]>>|<cell|=>|<cell|<big|int><rsub|-\<infty\>><rsup|\<infty\>>\<cal-N\><around*|(|x\|\<mu\>,\<sigma\><rsup|2>|)>x<rsup|2>\<mathd\>x=\<mu\><rsup|2>+\<sigma\><rsup|2>>>|<row|<cell|var<around*|[|x|]>>|<cell|=>|<cell|\<bbb-E\><around*|[|x<rsup|2>|]>-\<bbb-E\><around*|[|x|]><rsup|2>=\<sigma\><rsup|2>>>>>
    </eqnarray*>
  </hidden>|<\hidden>
    <\tit>
      The Multivariate Gaussian
    </tit>

    <space|6em><image|img/slide_multivariate_gaussian.png|.6par|||>
  </hidden>|<\hidden>
    <\tit>
      Gaussian Parameter Estimation
    </tit>

    Now suppose that we have a data set of observations

    <\equation*>
      <math-up|><math-up|<strong|x>>= (x<rsub|1>, . . . , x<rsub|N>)<rsup|T>,
    </equation*>

    representing <math|N> observations of the scalar variable <math|x>. Note
    that we are using the typeface <math|<math-up|<strong|x>>> to distinguish
    this from a single observation of the vector-valued variable
    <math|(x<rsub|1>, . . . , x<rsub|D>)<rsup|T>>, which we denote by
    <math|\<b-x\>>.

    We shall suppose that the observations are drawn independently from a
    Gaussian distribution whose mean <math|\<mu\>> and variance
    <math|\<sigma\><rsup|2>> are unknown, and we would like to determine
    these parameters from the data set.

    Data points that are drawn independently from the same distribution are
    said to be <em|independent and identically distributed>, which is often
    abbreviated to i.i.d.

    \;
  </hidden>|<\hidden>
    We have seen that the joint probability of two independent events is
    given by the product of the marginal probabilities for each event
    separately.

    Because our data set <math|<math-up|<strong|x>>> is i.i.d., we can
    therefore write the probability of the data set, given <math|\<mu\>> and
    <math|\<sigma\><rsup|2>>, in the form

    <\equation>
      p<around*|(|<math-up|<strong|x>>\|\<mu\>,\<sigma\><rsup|2>|)>=<big|prod><rsub|n=1><rsup|N>\<cal-N\><around*|(|x<rsub|n>\|\<mu\>,\<sigma\><rsup|2>|)><label|1.53>
    </equation>

    When viewed as a function of <math|\<mu\>> and <math|\<sigma\><rsup|2>>,
    this is the likelihood function for the Gaussian and is interpreted
    diagrammatically in Figure <reference|fig1.14>.
  </hidden>|<\hidden>
    \;

    <small-figure|<image|img/fig_1_14_likelihood_for_gaussian.png|.45par|||>|<label|fig1.14>Illustration
    of the likelihood function for a Gaussian distribution, shown by the red
    curve. Here the black points denote a data set of values
    <math|{x<rsub|n>}>, and the likelihood function given by (1.53)
    corresponds to the product of the blue values. Maximizing the likelihood
    involves adjusting the mean and variance of the Gaussian so as to
    maximize this product.>
  </hidden>|<\hidden>
    <tit|maximize the likelihood function>

    \;

    One common criterion for determining the parameters in a probability
    distribution using an observed data set is to find the parameter values
    that maximize the likelihood function.\ 

    This might seem like a strange criterion because, from our foregoing
    discussion of probability theory, it would seem more natural to maximize
    the probability of the parameters given the data, not the probability of
    the data given the parameters.

    In fact, these two criteria are related, as we shall discuss in the
    context of curve fitting.
  </hidden>|<\hidden>
    <tit|log of the likelihood>

    For the moment, however, we shall determine values for the unknown
    parameters <math|\<mu\>> and <math|\<sigma\><rsup|2>> in the Gaussian by
    maximizing the likelihood function<eqref|1.53>.\ 

    In practice, it is more convenient to maximize the log of the likelihood
    function. Because the logarithm is a monotonically increasing function of
    its argument, maximization of the log of a function is equivalent to
    maximization of the function itself.

    Taking the log not only simplifies the subsequent mathematical analysis,
    but it also helps numerically because the product of a large number of
    small probabilities can easily underflow the numerical precision of the
    computer, and this is resolved by computing instead the sum of the log
    probabilities.

    \;
  </hidden>|<\hidden>
    \;

    \;

    \;

    From (1.46) and (1.53), the log likelihood function can be written in the
    form

    <\equation>
      ln p<around*|(|<math-up|<strong|x>>\|\<mu\>,\<sigma\><rsup|2>|)>=-<frac|1|2\<sigma\><rsup|2>><big|sum><rsub|n=1><rsup|N><around*|(|x<rsub|n>-\<mu\>|)><rsup|2>-<frac|N|2>ln
      \<sigma\><rsup|2>-<frac|N|2>ln<around*|(|2\<pi\>|)>.<label|1.54>
    </equation>

    \;
  </hidden>|<\hidden>
    <tit|<math|\<mu\><rsub|ML>>>

    Maximizing Eq. <eqref|1.54> with respect to <math|\<mu\>>, we obtain the
    maximum likelihood solution given by

    <\equation>
      \<mu\><rsub|ML>=<frac|1|N><big|sum><rsub|n=1><rsup|N>x<rsub|n><label|1.55>
    </equation>

    which is the<em| sample mean>, i.e., the mean of the observed values
    <math|{x<rsub|n>}>.
  </hidden>|<\hidden>
    <tit|<math|\<sigma\><rsup|2><rsub|ML>>>

    Similarly, maximizing Eq. <eqref|1.54> with respect to
    <math|\<sigma\><rsub|2>>, we obtain the maximum likelihood solution for
    the variance in the form

    <\equation>
      \<sigma\><rsup|2><rsub|ML>=<frac|1|N><big|sum><rsub|n=1><rsup|N><around*|(|x<rsub|n>-\<mu\><rsub|ML>|)><rsup|2><label|1.56>
    </equation>

    which is the <em|sample variance> measured with respect to the sample
    mean <math|\<mu\><rsub|ML>>.\ 

    Note that we are performing a joint maximization of Eq. <eqref|1.54> with
    respect to <math|\<mu\>> and <math|\<sigma\><rsup|2>>, but in the case of
    the Gaussian distribution the solution for <math|\<mu\>> decouples from
    that for <math|\<sigma\><rsup|2>> so that we can first evaluate Eq.
    <eqref|1.55> and then subsequently use this result to evaluate Eq.
    <eqref|1.56>.
  </hidden>|<\hidden>
    \;

    Later in this chapter, and also in subsequent chapters, we shall
    highlight the significant limitations of the maximum likelihood approach.
    Here we give an indication of the problem in the context of our solutions
    for the maximum likelihood parameter settings for the univariate Gaussian
    distribution.\ 

    In particular, we shall show that the maximum likelihood approach
    systematically underestimates the variance of the distribution. This is
    an example of a phenomenon called bias and is related to the problem of
    over-fitting encountered in the context of polynomial curve fitting.

    We first note that the maximum likelihood solutions
    <math|\<mu\><rsub|ML>> and <math|\<sigma\><rsup|2><rsub|ML>> are
    functions of the data set values <math|x<rsub|1>, . . . , x<rsub|N>>.
    Consider the expectations of these quantities with respect to the data
    set values, which themselves come from a Gaussian distribution with
    parameters <math|\<mu\>> and <math|\<sigma\><rsup|2>>. It is
    straightforward to show that

    <\eqnarray*>
      <tformat|<table|<row|<cell|\<bbb-E\><around*|[|\<mu\><rsub|ML>|]>>|<cell|=>|<cell|\<mu\>>>|<row|<cell|\<bbb-E\><around*|[|\<sigma\><rsup|2><rsub|ML>|]>>|<cell|=>|<cell|<around*|(|<frac|N-1|N>|)>\<sigma\><rsup|2>>>>>
    </eqnarray*>
  </hidden>>
</body>

<\initial>
  <\collection>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|16:9>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|1.2|<tuple|1|?>>
    <associate|1.3|<tuple|2|?>>
    <associate|1.4|<tuple|3|?>>
    <associate|1.43|<tuple|7|?>>
    <associate|1.5|<tuple|4|?>>
    <associate|1.53|<tuple|8|?>>
    <associate|1.54|<tuple|9|?>>
    <associate|1.55|<tuple|10|?>>
    <associate|1.56|<tuple|11|?>>
    <associate|1.6|<tuple|5|?>>
    <associate|1.8|<tuple|6|?>>
    <associate|auto-1|<tuple|1|1>>
    <associate|auto-10|<tuple|8|?>>
    <associate|auto-11|<tuple|9|?>>
    <associate|auto-12|<tuple|10|?>>
    <associate|auto-13|<tuple|11|?>>
    <associate|auto-14|<tuple|12|?>>
    <associate|auto-15|<tuple|13|?>>
    <associate|auto-16|<tuple|14|?>>
    <associate|auto-2|<tuple|2|1>>
    <associate|auto-3|<tuple|3|1>>
    <associate|auto-4|<tuple|4|1>>
    <associate|auto-5|<tuple|5|?>>
    <associate|auto-6|<tuple|1|?>>
    <associate|auto-7|<tuple|6|2>>
    <associate|auto-8|<tuple|7|1>>
    <associate|auto-9|<tuple|2|?>>
    <associate|fig1.10|<tuple|10|?>>
    <associate|fig1.14|<tuple|14|?>>
    <associate|fig1.2|<tuple|2|?>>
    <associate|fig1.4|<tuple|4|?>>
    <associate|fig1.7|<tuple|7|1>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|figure>
      <tuple|normal|<surround|<hidden-binding|<tuple>|1>||Examples of
      hand-written digits taken from US zip codes.>|<pageref|auto-1>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|2>||Plot of a training
      data set of <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|N=10>>
      points, shown as blue circles, each comprising an observation of the
      input variable <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|x>>
      along with the corresponding target variable
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|t>>.
      The green curve shows the function <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|sin(2\<pi\>x)>>
      used to generate the data. Our goal is to predict the value of
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|t>>
      for some new value of <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|x>>,
      without knowledge of the green curve.>|<pageref|auto-2>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|3>||The error function
      (<reference|1.2>) corresponds to (one half of) the sum of the squares
      of the displacements (shown by the vertical green bars) of each data
      point from the function <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|y(x,
      w)>>.>|<pageref|auto-3>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|4>||Plots of
      polynomials having various orders <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M>>
      , shown as red curves, fitted to the data set shown in Figure
      <reference|fig1.2>.>|<pageref|auto-4>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|5>||Graphs of the
      root-mean-square \ error, defined by (<reference|1.3>), evaluated on
      the training set and on an independent test set for various values of
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M>>
      .>|<pageref|auto-5>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|6>||Plots of the
      solutions obtained by minimizing the sum-of-squares error function
      using the <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M
      = 9>> polynomial for <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|N
      = 15>> data points (left plot) and <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|N
      = 100>> data points (right plot). We see that increasing the size of
      the data set reduces the over-fitting problem.>|<pageref|auto-7>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|7>||Plots of
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M=9>>
      polynomials fitted to the data set shown in Figure <reference|fig1.2>
      using the regularized error function (<reference|1.4>) for two values
      of the regularization parameter <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<lambda\>>>
      corresponding to <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|ln
      \<lambda\> = \<minus\>18>> and <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|ln
      \<lambda\> = 0>>. The case of no regularizer, i.e.,
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<lambda\>
      = 0>>, corresponding to <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|ln
      \<lambda\> = \<minus\>\<infty\>>>, is shown at the bottom right of
      Figure <reference|fig1.4>.>|<pageref|auto-8>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|8>||Graph of the
      root-mean-square error (<reference|1.3>) versus
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|ln
      \<lambda\>>> for the <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M
      = 9>> polynomial.>|<pageref|auto-10>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|9>||We use a simple
      example of two coloured boxes each containing fruit (apples shown in
      green and oranges shown in orange) to introduce the basic ideas of
      probability.>|<pageref|auto-11>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|10>||We can derive the
      sum and product rules of probability by considering two random
      variables, <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|X>>,
      which takes the values <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|{x<rsub|i>}>>
      where <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|i=1,\<cdots\>,M>>,
      and <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|Y>>,
      which takes the values <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|{y<rsub|j>}>>
      where <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|j=1,\<cdots\>,L>>.
      In this illustration we have <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M
      = 5>> and<with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|
      L = 3>>. If we consider a total number
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|N>>
      of instances of these variables, then we denote the number of instances
      where <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|X
      = x<rsub|i>>> and <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|Y
      = y<rsub|j>>> by <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|n<rsub|i
      j>>>, which is the number of points in the corresponding cell of the
      array. The number of points in column
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|i>>,
      corresponding to <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|X
      = x<rsub|i>>>, is denoted by <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|c<rsub|i>>>,
      and the number of points in row <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|j>>,
      corresponding to <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|Y
      = y<rsub|j>>>, is denoted by <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|r<rsub|j>>>.>|<pageref|auto-12>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|11>||An illustration of
      a distribution over two variables, <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|X>>,
      which takes <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|9>>
      possible values, and <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|Y>>,
      which takes two possible values. The top left figure shows a sample of
      60 points drawn from a joint probability distribution over these
      variables. The remaining figures show histogram estimates of the
      marginal distributions <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|p(X)>>
      and <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|p(Y)>>,
      as well as the conditional distribution
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|p(X\|Y
      = 1)>> corresponding to the bottom row in the lower
      right.>|<pageref|auto-13>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|12>||The concept of
      probability for \ discrete variables can be extended to that of a
      probability density <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|p(x)>>
      over a continuous variable <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|x>>
      and is such that the probability of
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|x>>
      lying in the interval <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|(x,
      x + \<delta\>x)>> is given by <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|p(x)\<delta\>x>>
      for <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<delta\>x
      \<rightarrow\> 0>>. The probability density can be expressed as the
      derivative of a cumulative distribution function
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|P(x)>>.>|<pageref|auto-14>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|13>||Plot of the
      univariate Gaussian \ showing the mean
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<mu\>>>
      and the standard deviation <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<sigma\>>>.>|<pageref|auto-15>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|14>||Illustration of
      the likelihood function for a Gaussian distribution, shown by the red
      curve. Here the black points denote a data set of values
      <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|{x<rsub|n>}>>,
      and the likelihood function given by (1.53) corresponds to the product
      of the blue values. Maximizing the likelihood involves adjusting the
      mean and variance of the Gaussian so as to maximize this
      product.>|<pageref|auto-16>>
    </associate>
    <\associate|table>
      <tuple|normal|<surround|<hidden-binding|<tuple>|1>||Table of the
      coefficients w for \ polynomials of various order. Observe how the
      typical magnitude of the coefficients increases dramatically as the
      order of the polynomial increases.>|<pageref|auto-6>>

      <tuple|normal|<surround|<hidden-binding|<tuple>|2>||Table of the
      coefficients <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<b-w\><rsup|\<ast\>>>>
      for <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|M
      = \ 9>> polynomials with various values for the regularization
      parameter <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<lambda\>>>.
      Note that ln <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<lambda\>
      = \<minus\>\<infty\>>> corresponds to a model with no regularization,
      i.e., to the graph at the bottom right in Figure <reference|fig1.4>. We
      see that, as the value of <with|color|<quote|#503050>|font-family|<quote|rm>|<with|mode|<quote|math>|\<lambda\>>>
      increases, the typical magnitude of the coefficients gets
      smaller.>|<pageref|auto-9>>
    </associate>
  </collection>
</auxiliary>