# +LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{etex}
#+LATEX_HEADER: \usepackage{amsmath}
 # +LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}
 # +LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}
#+LATEX_HEADER: \newcommand*\diff{\mathop{}\!\mathrm{d}}
#+LATEX_HEADER: \allowdisplaybreaks
#+LATEX_HEADER:\usepackage{polynom}


#+startup: beamer
#+LaTeX_CLASS: beamer
# +LaTeX_CLASS_OPTIONS: [bigger]
 # +latex_header:  \usepackage{beamerarticle}
# +latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# +latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  线性系统时域分析法
#+latex_header: \subtitle{系统的稳态误差计算}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:











* 误差传递函数
** 系统误差
*** ignore					      :BMCOL:B_ignoreheading:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: ignoreheading
     :END:
\begin{psmatrix}[rowsep=0.4,colsep=0.5]
%              
%         E(s) .------.
% R-->o----- ->| G(s) |--+--> C
%   _ ^        '------'  |
%     |                  |  
%     '--------[ H(s) ]--'
%
%
% 1                        2                        3             4              5    6
$R(s)$ &  \pscirclebox[framesep=-0.2em]{$\times$} &$\cdots $   &  \psframebox{$G(s)$}   &   & $C(s)$ \\
       &                                          &       &  \psframebox{$H(s)$}&  &        \\
%link
\ncline{->}{1,1}{1,2}
\ncline{->}{1,2}{1,4}
\naput{$E(s)$}
\ncline{->}{1,4}{1,6}
\ncangle[angleA=0,angleB=0,armA=0.5em,armB=0.5em]{1,4}{2,4}
\ncangle[angleA=180,angleB=-90,armA=0.5em,armB=1em]{->}{2,4}{1,2}
\naput[npos=2.3]{$-$}
\end{psmatrix}

\mode<article>{系统误差有两种:}

 * <2->输入端定义:$E_{2}(s)=E(s)$
 * <3->输出端定义:$E_{1}(s)=C_{expect}-C_{real}$
 * <4->不加特别说明,系统误差指的是输入端定义.

*** $E(s)$ 与 $E_1(s)$					      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <5->
     :END:

\begin{eqnarray*}
C_{expect} & = & \frac{R(s)}{H(s)}\\
E_{1}(s)   & = & \frac{R(s)}{H(s)}-C(s) \\
           & = & \frac{R(s)-C(s)H(s)}{H(s)}\\
           & =& \frac{E(s)}{H(s)}
\end{eqnarray*}

** 误差传递函数:
\begin{eqnarray*}
\Phi_{e}(s) & = & \frac{E(s)}{R(s)}\\
            & = & \frac{1}{1+G(s)H(s)} \\
            & = & \frac{R(s)-H(s)C(s)}{R(s)} \\
            & = & 1-H(s)\Phi(s)
\end{eqnarray*}

 * <2-> 系统误差:$E(s)=\Phi_{e}(s)R(s)$

** 稳态误差:
\begin{eqnarray*}
e_{ss} &=& \lim_{t\rightarrow \infty}e(t) \\
       &=& \lim_{s\rightarrow 0}sE(s)  \\
       &= & \lim_{s\rightarrow 0}s\Phi_{e}(s)R(s)
\end{eqnarray*}

    * <2->稳态误差与输入信号有关
    * <3->求稳态误差前要判断系统稳定性

** 扰动作用下的稳态误差
\begin{psmatrix}[rowsep=0.4,colsep=0.5]
%          1    2  3     4    5    6    7 
%                            | N(s)
%               E(s)         v +  
%         R---->o--> G_1(s)--o- G_2(s)--+--> C
%             _ ^                       |
%               |                       |  
%               '-----------H(s)--------+
%           
%
% 1                         2                           3                  4                     5
       &                                       &               &                        &         $N(s)$                                  &   \\  
$R(s)$  &\pscirclebox[framesep=-0.2em]{$\times$}& {\hskip 1em} &  \psframebox{$G_1(s)$} &  \pscirclebox[framesep=-0.2em]{$\times$} &  \psframebox{$G_2(s)$}  & \    & $C(s)$ \\
       &                                         &              &     &   \psframebox{$ H(s) $} 
%link
\ncline{->}{1,5}{2,5}
%\naput{$N(s)$}
\ncline{->}{2,1}{2,2}
\ncline{->}{2,2}{2,4}
\naput{$E(s)$}
\ncline{->}{2,4}{2,5}
\ncline{->}{2,5}{2,6}
\ncline{->}{2,6}{2,8}
\ncangles[angleA=180,angleB=0,armA=0em,armB=0em]{->}{2,7}{3,5}
\ncangle[angleA=180,angleB=-90,armA=0em,armB=0em]{->}{3,5}{2,2}
\naput[npos=1.6]{$-$}
\end{psmatrix}

*** 输入端定义:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:

\begin{eqnarray*}
E(s) & = &E_R(s)+E_N(s) \\
E_R(s)&=& \Phi_e(s)R(s) \\
E_N(s)&=& \Phi_{en}(s)N(s) \\
\end{eqnarray*}

*** 输出端定义:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <3->
     :END:
令 $R(s)=0$ ,计算 $N(s)$ 单独引起的 $e_{ss}$ ,此时 $C_{expect}(s)=0$ 

\begin{eqnarray*}
E(s) & = & 0-C(s) \\
     & = & -\Phi_N(s)N(s)\\
\Phi_N(s) &=& \frac{G_2}{1+G_1G_2}\\
e_{ss}&=&\lim_{s\rightarrow 0}s(-\Phi_N(s)N(s)) 
\end{eqnarray*}

* 系统类型与静态误差系数
** 阶跃输入:
\begin{eqnarray*}
r(t) & = & A \\
R(s) & = & \frac{A}{s} \\
e_{ss}&=& \lim_{s\rightarrow 0}s \cdot\frac{1}{1+G_{open}(s)}\cdot\frac{A}{s} \\
      &=& \lim_{s\rightarrow 0}\frac{A}{1+G_{open}(s)}
\end{eqnarray*}

** 速度输入
\begin{eqnarray*}
r(t) & = & vt \\
R(s) & = & \frac{v}{s^{2}} \\
e_{ss}&=& \lim_{s\rightarrow 0}s \cdot\frac{1}{1+G_{open}(s)}\cdot\frac{v}{s^{2}} \\
      &=& \lim_{s\rightarrow 0}\frac{A}{s+sG_{open}(s)}\\
      &=& \lim_{s\rightarrow 0}\frac{A}{sG_{open}(s)}
\end{eqnarray*}

** 加速度输入
\begin{eqnarray*}
r(t) & = & \frac{1}{2}at^{2} \\
R(s) & = & \frac{a}{s^{2}} \\
e_{ss}&=& \lim_{s\rightarrow 0}s \cdot\frac{1}{1+G_{open}(s)}\cdot\frac{a}{s^{3}} \\
      &=& \lim_{s\rightarrow 0}\frac{A}{s^{2}+s^{2}G_{open}(s)}\\
      &=& \lim_{s\rightarrow 0}\frac{A}{s^{2}G_{open}(s)}
\end{eqnarray*}

** 系统类型
 * <2->由开环传递函数定义
     \begin{eqnarray*}
      G_{open} & = & G(s)H(s) \\
	       & = & \frac{K\prod_{i=1}^{m}(\tau_{i}s+1)}{s^{\nu}\prod_{j=1}^{n-\nu}(T_{j}s+1)}
     \end{eqnarray*}
 * <2->其中 $K$ 为开环增益.
 * <3->定义:
   * $\nu=0$ 称为0型系统
   * $\nu=1$ 称为I型系统
   * $\nu=2$ 称为II型系统

** 静态误差系数
 *  <2->静态位置误差系数
       \begin{eqnarray*}
       r(t) &=& A\\
       e_{ss}&=&\frac{A}{1+K_{p}}, \qquad
       K_{p}=\lim_{s\rightarrow 0} G_{open}(s)
       \end{eqnarray*}
 *  <3->静态速度误差系数 
       \begin{eqnarray*}
       r(t)&=&vt\\
       e_{ss}&=&\frac{v}{K_{v}}, \qquad
       K_{v}=\lim_{s\rightarrow 0} sG_{open}(s)
       \end{eqnarray*}
 *  <4->静态加速度误差系数 
       \begin{eqnarray*}
       r(t)&=&\frac{1}{2}at^{2}\\
       e_{ss}&=&\frac{a}{K_{a}}, \qquad
       K_{a}=\lim_{s\rightarrow 0} s^{2}G_{open}(s)
       \end{eqnarray*}
** 零型系统($\nu=0$)
 * <2-> $r(t)=A$ 时:
     \begin{eqnarray*}
     K_p &=& \lim_{s\rightarrow 0}G_o(s) 
	 = \lim_{s\rightarrow 0}\frac{K\prod_{i=0}^m(\tau_i s+1)}{\prod_{j=1}^n (\tau_j s+1)} 
	 = K \\
     e_{ss1} &=& \frac{A}{1+K_p}
     \end{eqnarray*}
     \mode<article>{称为有差系统.}
 * <3-> $r(t)=vt$ 时:
     \begin{eqnarray*}
     K_v &=& \lim_{s\rightarrow 0}sG_o(s) 
	 = 0 \\
     e_{ss2} &=& \infty 
     \end{eqnarray*}
 * <4> $r(t)=\frac{1}{2}at^2$ 时:
     \begin{eqnarray*}
     K_a &=& \lim_{s\rightarrow 0}s^2 G_o(s) 
	 = 0 \\
     e_{ss3} &=& \infty
     \end{eqnarray*}

** I型系统($\nu=1$)
 *  <2->$r(t)=A$ 时:
     \begin{eqnarray*}
     K_p &=& \lim_{s\rightarrow 0}G_o(s) 
	 = \lim_{s\rightarrow 0}\frac{K\prod_{i=0}^m(\tau_i s+1)}{s\prod_{j=1}^{n-1}(\tau_j s+1)} 
	 = \infty \\
     e_{ss1} &=& \frac{1}{1+K_p}
	   = 0
     \end{eqnarray*}
     \mode<article>{无差系统.}
 *  <3->$r(t)=vt$ 时:
     \begin{eqnarray*}
     K_v &=& \lim_{s\rightarrow 0}sG_o(s) 
	 = K \\
     e_{ss2} &=& \frac{v}{K_v} 
	     =\frac{v}{K}
     \end{eqnarray*}
 *  <4->$r(t)=\frac{1}{2}at^2$ 时:
     \begin{eqnarray*}
     K_a &=& \lim_{s\rightarrow 0}s^2 G_o(s) 
	 = 0 \\
     e_{ss3} &=& \infty
     \end{eqnarray*}
** II型系统($\nu=2$)
\begin{eqnarray*}
K_p & = & \infty\\
e_{ss1} &=& 0 \\
K_v & = & \infty \\
e_{ss2} &=& 0 \\
K_a &=& K \\
e_{ss3} &=& \frac{a}{K}
\end{eqnarray*}
** 小结:
 * <2->零型:
     \[e_{ss1}=\frac{A}{1+K},e_{ss2}=e_{ss3}=\infty\]
 * <3->I型:
     \[e_{ss1}=0,e_{ss2}=\frac{v}{K},e_{ss3}=\infty\]
 * <4->II型:
     \[e_{ss1}=e_{ss2}=0,e_{ss3}=\frac{a}{K}\]
** 例:

若 $G(s)H(s) =\frac{10K_h}{s+1},K_h\in\{0.1,1\}$ ,求单位阶跃下的 $e_{ss}$ .

\mode<article>{解:}

*** 解法1						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:

零型系统, $r(t)=1,e_{ss}=\frac{1}{1+K_p}$

\begin{eqnarray*}
K_p &=  &\lim_{s\rightarrow 0}G(s)H(s) \\
    &=& 10K_h \\
    &=&
\begin{cases}
1  & K_h =0.1 \\
10 & K_h = 1
\end{cases}\\
e_{ss} &=&
\begin{cases}
0.5 & K_h=0.1 \\
\frac{1}{11} & K_h=1
\end{cases}
\end{eqnarray*}

*** 解法2:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :BEAMER_env: block
     :BEAMER_envargs: <3->
     :END:

\begin{eqnarray*}
e_{ss} &=& \lim_{s\rightarrow 0}s\Phi_e(s)R(s)\\
    &=&\lim_{s\rightarrow 0}s\frac{1}{1+G(s)H(s)}R(s)\\
    &=&\lim_{s\rightarrow 0}s\frac{s+1}{s+1+10K_h}\frac{1}{s}\\
    &=& \frac{1}{1+10K_h} \\
    &=&
\begin{cases}
0.5 & K_h=0.1 \\
\frac{1}{11} & K_h=1
\end{cases}
\end{eqnarray*}

** 例:  求 $r(t)=2+3t$ 时的 $e_{ss}$
\begin{psmatrix}[rowsep=0.4,colsep=0.5]
% 1    2   3  4   5   6    7       8   9
%           R*    E(s)    .------.
% R-->2/s+1-->o------>o-->| G(s) |--+--> C
%           _ ^     _ ^   '------'  |
%             |       |             |  
%             |       '----0.8s-----+
%             |                     |
%             '---------------------'
%        
%
% 1                        2                 3        
$R(s)$ &  \psframebox{$\frac{2}{s+1}$} & ${\hskip 1em}  $ & %
\pscirclebox[framesep=-0.2em]{$\times$} &$ $   & \pscirclebox[framesep=-0.2em]{$\times$} & %
\psframebox{$\frac{5}{s(5s+1)}$}   & \   & $C(s)$ \\
  &   &     &  & & & \psframebox{$ 0.8s $} &  \ &  \\
\\
%link
\ncline{->}{1,1}{1,2}
\ncline{->}{1,2}{1,4}
\naput{$R^{*}(s)$}
\ncline{->}{1,4}{1,6}
\naput{$E(s)$}
\ncline{->}{1,6}{1,7}
\ncline{->}{1,7}{1,9}
\ncline{2,8}{2,7}
\ncangle[angleA=180,angleB=-90,armA=0.5em,armB=1em]{->}{2,7}{1,6}
\naput[npos=2.3]{$-$}
\ncangles[angleA=180,angleB=-90,armA=0em,armB=4.5em]{->}{1,8}{1,4}
\naput[npos=3.6]{$-$}
\end{psmatrix}

解:

\begin{eqnarray*}
G(s) & = \frac{C(s)}{E(s)} \\
     &=& \frac{\frac{5}{s(5s+1)}}{1+\frac{4s}{s(5s+1)}} \\
    & = & \frac{5}{5s^2+5s} \\
    & = & \frac{1}{s(s+1)} 
\end{eqnarray*}

** 例:计算稳态误差
\mode<article>{判断稳定性:}

\begin{eqnarray*}
\Phi(s) &=& \frac{C(s)}{R^{*}(s)}
        = \frac{1}{s(s+1)+1} \\
\Phi_e(s) &=& \frac{s(s+1)}{s(s+1)+1}
\end{eqnarray*}
系统稳定.

\begin{eqnarray*}
R(s) &=& \frac{2s+3}{s^2}\\
e_{ss} & = &\lim_{s\rightarrow 0}s\Phi_e(s)R^{*}(s) \\
       &=& \lim_{s\rightarrow 0}s\cdot\frac{s(s+1)}{s(s+1)+1}\cdot\frac{2}{s+1}\cdot\frac{2s+3}{s^2} \\
       &=& 6
\end{eqnarray*}

* 动态误差系数
** 动态误差系数
动态误差系数可描述系统稳态误差随时间变化的规律，静态误差可看作动态误差的一个特例.

\begin{eqnarray*}
E(s) & = & \Phi_e(s)R(s)\\
\Phi_e(s) &=& \frac{E(s)}{R(s)}\\
         &=&\frac{1}{1+G(s)H(s)} \\
         &=& \frac{M(s)}{N(s)} 
\end{eqnarray*}

** 在 $s=0$ 处展开,得:

\begin{eqnarray*}
\phi_e(s)  &=& \Phi_e(0)+\dot{\Phi}_e(0)s+\cdots+\frac{\Phi_e^{(n)}(0)s^n}{n!}+\cdots \\
E(s) & = & \Phi_e(0)R(s)+\dot{\Phi}_e(0)sR(s)+\cdots+\frac{\Phi_e^{(n)}(0)s^nR(s)}{n!}+\cdots \\
e_{ss}(t) & = & \Phi_e(0)r(t)+\dot{\Phi}_e(0)\dot{r}(t)+\cdots+\frac{\Phi_e^{(n)}(0)r^{(n)}(t)}{n!}+\cdots \\
          &= & \sum_{i=1}^{\infty}C_ir^{(i)}(t) ,\qquad
C_i = \frac{\Phi_e^{(i)}(0)}{i!}
\end{eqnarray*}

  * 其中 $C_i$ 称为动态误差系数.
      * $C_0$ 动态位置误差系数
      * $C_1$ 动态速度误差系数
      * $C_2$ 动态加速度误差系数

** 动态误差系数示例:
  * <2-> 零型系统 $r(t)=1$ 则 \[e_{ss}(t)=C_0 ,C_0=\frac{1}{1+K_p}\]
  * <3-> I型系统 $r(t)=t$ 则 \[e_{ss}(t)=C_0 t+C_1,C_0=0,C_1=\frac{1}{K_v}\]
  * <4-> II型系统 $r(t)=t$ 则 \[e_{ss}(t)=C_0 \frac{1}{2}at^2+C_1at+C_2 a,C_0=C_1=0,C_2=\frac{1}{K_a}\]

** 讨论: $C_i$ 的计算
\begin{eqnarray*}
\Phi_e(s) &=& \frac{M(s)}{N(s)} \\
 & = & C_0+C_1s+C_2s^2+\cdots
\end{eqnarray*}

** 例: $G(s)H(s)=\frac{1}{s(s+1)}$

# 依次除以 $s$,并取极限.
# \begin{eqnarray*}
# \Phi_e(s) & = & \frac{s^2+s}{s^2+s+1} \\
# C_0 &=& \lim_{s\rightarrow 0}\Phi_e(s) 
#     = \lim_{s\rightarrow 0}\frac{s^2+s}{s^2+s+1} 
#     = 0 \\
# C_1 &=& \lim_{s\rightarrow 0}\frac{\Phi_e(s)-C_0}{s} 
#     = \lim_{s\rightarrow 0}\frac{s^2+s}{s(s^2+s+1)} 
#     = 1 \\
# C_2 &=& \lim_{s\rightarrow 0}\frac{\Phi_e(s)-C_0-C_1 s}{s^2} 
#     = \lim_{s\rightarrow 0}\frac{-s^3}{s^2(s^2+s+1)}
#     = 0 \\
# C_3 &=& \lim_{s\rightarrow 0}\frac{\Phi_e(s)-C_0-C_1 s-C_2 s^2}{s^3}
#     = \lim_{s\rightarrow 0}\frac{-s^3}{s^2+s+1}
#      = -1 
# \end{eqnarray*}
# 
# ** 综合除法
# *** 综合除法:
综合除法:

\[
\begin{matrix}
\text{divident}      &      &   \text{divisor}  &    & \text{quotient} &   & \text{remainder} \\  
s^2+s             &\div  &    s^2+s+1     & \rightarrow &  s       &  & s^2+s-s(1+s+s^2) \\
-s^3             &\div  &   s^2+s+1       & \rightarrow  & -s^3     &   & -s^3-(-s^3)(1+s+s^2)\\
 s^4+s^5         &\div  &  s^ 2+s+1       & \rightarrow & s^4  &   & \cdots  \\
\cdots           &\div   &  s^2+s+1       &\rightarrow  & \cdots   &    &\cdots   
\end{matrix}
\]

得:
\begin{eqnarray*}
\Phi_e(s)  &=& s-s^3+s^4+\cdots
\end{eqnarray*}

** 例: $G(s)H(s)=\frac{1}{s(s+1)}$ 另一种写法:

\begin{eqnarray*}
\frac{s^2+s}{s^2+s+1} & = & s + \frac{-s^2+s-s(1+s+s^2)}{s^2+s+1}  \\
\frac{-s^3}{s^2+s+1}  & = & -s^3+\frac{-s^3-(-s^3)(1+s+s^2)}{s^2+s+1}\\
\frac{s^4+s^5}{s^2+s+1} &=& s^4 +\cdots \\
\cdots                  &=& \cdots \\
\Phi_e(s)               &=& s-s^3+s^4+\cdots
\end{eqnarray*}

** 例: $G(s)H(s)=\frac{1}{s(s+1)}$ 长除法
# \polylongdiv{s^2+s}{s^2+s+1}
\[ 
\begin{array}{ccccccccc} 
 & & s &  & -s^3 & +s^4 &  &\cdots\\
\cline{2-8}
\multicolumn{1}{r|}{1+s+s^2} & & s & +s^2 \\
                             & & s  & +s^2 & +s^3 \\
\cline{3-5}
                             & &   &     & -s^3 \\
                             & &   &     & -s^3  & -s^4 & -s^5\\
\cline{5-7}
                             & &   &     &       &  s^4 &  +s^5\\
                             & &   &     &       &  s^4 &  +s^5  & +s^6\\
\cline{6-8}
                             & &   &     &       &      &       & -s^6\\
                             & &   &     &       &      &       & \cdots
\end{array} 
\]


** 例:
单位负反馈系统开环传递函数: $G_o(s)=\frac{100}{s(0.s1+1)}$ 求输入信号为 $\sin(5 t)$ 时的稳态误差.

解:系统稳定,
\begin{eqnarray*}
r(t) &=& sin(\omega t),\omega=5 \\
E(s) &=& \Phi_e(s)R(s) \\
e_{ss}&=& \sum_{i=0}^{\infty}C_i r^{(i)} \\
\Phi_e(s)&=& \frac{1}{1+G_o(s)} \\
         &=& \frac{0.1s^2+s}{0.1s^2+s+100} 
\end{eqnarray*}

** 解法1


# %\begin{matrix}
# %0.1s^2+s            & \div & 0.1s^2+s+100  & \rightarrow &  0.01s   & 0.1s^2+s-0.01s(0.1s^2+s+100) \\
# %-10^{-3}s^3+0.09s^2 & \div & 0.1s^2+s+100  & \rightarrow &  9\times 10^{-4}s^2 & -10^{-3}s^3+0.09s^2-9\times 10^{-4}s^2(0.1s^2+s+100) \\
# %-9\times 10^{-5}s^4-1.9\times 10^{-3}s^3 & \div & 0.1s^2+s+100  & \rightarrow & -1.9\times 10^{-5}s^3  & \cdots \\
# %\end{matrix}


 *  $\frac{0.1s^2+s}{0.1s^2+s+100}  =0.01s+\frac{0.1s^2+s-0.01s(0.1s^2+s+100)}{0.1s^2+s+100}$
 *  $\frac{-10^{-3}s^3+0.09s^2}{0.1s^2+s+100} = 9\times 10^{-4}s^2+\frac{-10^{-3}s^3+0.09s^2-9\times 10^{-4}s^2(0.1s^2+s+100)}{0.1s^2+s+100}$
 *  $\frac{-9\times 10^{-5}s^4-1.9\times 10^{-3}s^3}{0.1s^2+s+100}  = -1.9\times 10^{-5}s^3 + \cdots$
所以
  * $\Phi_e(s) = 0+0.01s+9\times 10^{-4}s^2-1.9\times 10^{-5}s^3+\cdots$
  * $e_{ss}(t) = (C_0-C_2\omega^2+C_4\omega^4+\cdots)\sin(\omega t)+(C_1-C_3\omega^3+C_5\omega^5+\cdots)\cos(\omega t)$
  * $e_{ss}(t) = -0.055\cos(5t-249^{\circ})$

** 解法2:
\begin{eqnarray*}
E(s) & = & \Phi_e(s)R(s) \\
     &=& \frac{s^2+10S}{s^2+10S+1000}\cdot\frac{5}{s^2+25}\\
     &=&\frac{-0.0498s-0.1115}{s^2+25}+\frac{as+b}{s^2+10s+1000}\\
e_{ss}(t)&=& -0.055\cos(5t-249^{\circ})+\Delta 
\end{eqnarray*}
其中: $\lim_{t\rightarrow\infty}\Delta = 0$


* 减小稳态误差的措施
** 减小 $e_{ss}$ 的措施
 * <2->增大开环增益
 * <3->提高系统类型
 * <4->串级控制抑制扰动
 * <5->复合控制
** 增大开环增益
\begin{align*}
G(s)    & = \frac{K\prod_{i=1}^{m}(\tau_{i}s+1)}{s^{\nu}\prod_{j=1}^{n-\nu}(T_{j}s+1)} \\
e_{ss}  &=
\begin{cases}
\frac{1}{1+K} & \nu=0,R(s)=\frac{1}{s} \\
\frac{1}{K} & \nu=1,R(s)=\frac{1}{s^2} \\
\frac{1}{K} & \nu=2,R(s)=\frac{1}{s^3} 
\end{cases}
\end{align*}
** 提高系统类型
\begin{align*}
G(s)    & = \frac{1}{s}\frac{K\prod_{i=1}^{m}(\tau_{i}s+1)}{s^{\nu}\prod_{j=1}^{n-\nu}(T_{j}s+1)} \\
e_{ss}  &=
\begin{cases}
\frac{1}{K} & \nu=0,R(s)=\frac{1}{s^2} \\
\frac{1}{K} & \nu=1,R(s)=\frac{1}{s^3} 
\end{cases}
\end{align*}
** 串级控制
\begin{psmatrix}[rowsep=0.4,colsep=0.5]
%          1    2  3     4    5    6    7 
%                            | N(s)
%               E(s)         v +  
%         R---->o-o-> G_1(s)--o- G_2(s)---G_3-+--> C
%             _ ^  \________H(s)________/     |
%               |                             |  
%               '-----------------------------+
%           
%
       &         &            &         &                        & $N(s)$    \\  
$R(s)$ & $\circ$ & \hskip 1em & $\circ$ &  \psframebox{$G_1(s)$} & $\circ$   &  \psframebox{$G_2(s)$} & \  & \psframebox{$G_3(s)$} & \  & $C(s)$ \\
       &         &            &         &                        &   \psframebox{$ H(s) $} 
%link
\ncline{->}{1,6}{2,6}
%naput{$N(s)$}
\ncline{->}{2,1}{2,2}
\ncline{->}{2,2}{2,4}
\naput{$E(s)$}
\ncline{->}{2,4}{2,5}
\ncline{->}{2,5}{2,6}
\ncline{->}{2,6}{2,7}
\ncline{->}{2,7}{2,9}
\ncline{->}{2,9}{2,11}
\ncangle[angleA=-90,angleB=0,armA=0em,armB=0em]{->}{2,8}{3,6}
\ncangle[angleA=180,angleB=-90,armA=0em,armB=0em]{->}{3,6}{2,4}
\naput[npos=1.6]{$-$}
\ncangles[angleA=-90,angleB=-90,armA=4em,armB=0em]{->}{2,10}{2,2}
\naput[npos=2.6]{$-$}
\end{psmatrix}


\begin{align*}
C(s) &=(G_1(s)E'(s)+N(s))G_2(s)G_3(s) \\
E'(s) &=E(s)-\frac{H(s)}{G_3(s)}C(s)\\
C(s) &=\frac{(G_1(s)E(s)+N(s))G_2(s)G_3(s)}{1+G_1(s)G_2(s)H(s)}\\
C(s) &\approx\frac{G_3(s)E(s)}{H(s)} \qquad (G_1(s)>>1) \\
\end{align*}
** 复合控制
\begin{psmatrix}[rowsep=0.4,colsep=0.5]
%   .-e/(1-e)-.         
%   |  E(s)   |   .------.
% R-->o-------o ->| G(s) |--+--> C
%   _ ^           '------'  |
%     |                     |  
%     '---------------------'
%
%
% 1          2         3          4                  5          6        7
       &          & \psframebox{$\frac{\epsilon}{1-\epsilon}$} \\
$R(s)$ &  $\circ$ & \hskip 1em & $\circ$  &  \psframebox{$G(s)$} & \  & $C(s)$ 
%link
\ncline{->}{2,1}{2,2}
\ncline{->}{2,2}{2,4}
\naput[labelsep=0pt]{$E(s)$}
\ncline{->}{2,4}{2,5}
\ncline{->}{2,5}{2,7}
\ncangles[angleA=0,angleB=180,armA=0.2em,armB=0.5em]{->}{2,1}{1,3}
\ncangle[angleA=0,angleB=90,armA=0em,armB=0.5em]{->}{1,3}{2,4}
\ncangles[angleA=-90,angleB=-90,armA=2em,armB=0em]{->}{2,6}{2,2}
\naput[npos=2.3]{$-$}
\end{psmatrix}


\begin{eqnarray*}
\epsilon &=& \frac{r(\infty)-c(\infty)}{r(\infty)}\\
c(\infty)&=& (1-\epsilon)r(\infty)\\
r(t)&=&\frac{r'(t)}{1-\epsilon}\\
c(\infty) &=& r'(\infty) \\
e'_{ss}&=&r'(\infty)-c(\infty)\\
 &=& 0
\end{eqnarray*}
