# +LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \pgfplotsset{compat=1.8}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}
#+LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [table]
# +LaTeX_CLASS_OPTIONS: [bigger]
#+latex_header:  \usepackage{beamerarticle}
# +latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# +latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  线性系统的频域分析法
#+latex_header: \subtitle{开环频率特性}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:










* 开环系统Nyquist图
** 开环系统Nyquist图 $G_o(s) =\frac{K\prod_{j=1}^m(\tau_j s+1)}{s^{\nu}\prod_{i=1}^{n-\nu}(T_i s+1)}$
 * 当  $\nu=0$  时,为零型系统:
     \begin{eqnarray*}
     \left. A(\omega)\right|_{\omega=0} & = & K\\
     \left. \phi(\omega)\right|_{\omega=0}&=&0 \\
     \lim_{\omega\rightarrow\infty} A(\omega)&=&0 \\
     \lim_{\omega\rightarrow\infty} \phi(\omega)&=& -(n-m)\times\frac{\pi}{2} 
     \end{eqnarray*}
** 开环系统Nyquist图(续) $G_o(s) =\frac{K\prod_{j=1}^m(\tau_j s+1)}{s^{\nu}\prod_{i=1}^{n-\nu}(T_i s+1)}$
 * 当  $\nu=1$  时 ,为I型系统:
     \begin{eqnarray*}
     \lim_{\omega\rightarrow 0} A(\omega) & = & \infty\\
     \lim_{\omega\rightarrow 0} \phi(\omega)&=&-\frac{\pi}{2} \\
     \lim_{\omega\rightarrow\infty} A(\omega)&=&0 \\
     \lim_{\omega\rightarrow\infty} \phi(\omega)&=& -(n-m)\times\frac{\pi}{2} 
     \end{eqnarray*}
** 开环系统Nyquist图(续)$G_o(s) =\frac{K\prod_{j=1}^m(\tau_j s+1)}{s^{\nu}\prod_{i=1}^{n-\nu}(T_i s+1)}$
 *  当  $\nu=2$  时,为II型系统:
     \begin{eqnarray*}
     \lim_{\omega\rightarrow 0} A(\omega) & = & \infty\\
     \lim_{\omega\rightarrow 0} \phi(\omega)&=&-\pi \\
     \lim_{\omega\rightarrow\infty} A(\omega)&=&0 \\
     \lim_{\omega\rightarrow\infty} \phi(\omega)&=& -(n-m)\times\frac{\pi}{2} 
     \end{eqnarray*}
** 开环系统Nyquist图(续)$G_o(s) =\frac{K\prod_{j=1}^m(\tau_j s+1)}{s^{\nu}\prod_{i=1}^{n-\nu}(T_i s+1)}$
 *  当  $\nu=3$  时,为III型系统:
     \begin{eqnarray*}
     \lim_{\omega\rightarrow 0} A(\omega) & = & \infty\\
     \lim_{\omega\rightarrow 0} \phi(\omega)&=&-\frac{3}{2}\pi \\
     \lim_{\omega\rightarrow\infty} A(\omega)&=&0 \\
     \lim_{\omega\rightarrow\infty} \phi(\omega)&=& -(n-m)\times\frac{\pi}{2} 
     \end{eqnarray*}

** 开环系统Nyquist图,例1
*** $G_o(s)=\frac{10}{s^{\nu}(0.1s+1)}$			      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <1->
     :END:

\begin{tikzpicture}[scale=0.5]
% $G_o(s)=\frac{10}{s^{\nu}(0.1s+1)}$ 
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-10,ymax=10,xmin=-10,xmax=10,every axis plot post/.append style={mark=none},
grid=both]
\addplot[blue,thick]shell {octave -q --eval "s=tf('s');nu=0;w=logspace(-1,3,30);g=10/s^nu/(0.1*s+1);[re,im]=nyquist(g,w);disp([re,im]);"};
\addplot[green,thick]shell {octave -q --eval "s=tf('s');nu=1;w=logspace(-1,2,20);g=10/s^nu/(0.1*s+1);[re,im]=nyquist(g,w);disp([re,im]);"};
\addplot[pink,thick]shell {octave -q --eval "s=tf('s');nu=2;w=logspace(-0.5,1,20);g=10/s^nu/(0.1*s+1);[re,im]=nyquist(g,w);disp([re,im]);"};
\addplot[red,thick]shell {octave -q --eval "s=tf('s');nu=3;w=logspace(-0.33,1,20);g=10/s^nu/(0.1*s+1);[re,im]=nyquist(g,w);disp([re,im]);"};
\legend{$\nu=0$ , $\nu=1$ , $\nu=2$ , $\nu=3$}
\end{axis}
\end{tikzpicture}

*** $G_o(s)=\frac{10}{(0.1s+1)^{n}}$			      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:

\begin{tikzpicture}[scale=0.5]
% $G_o(s)=\frac{10}{(0.1s+1)^n}$ 
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-10,ymax=5,xmin=-5,xmax=10,every axis plot post/.append style={mark=none},
grid=both]
\addplot[blue,thick]shell {octave -q --eval "s=tf('s');n=1;g=10/(0.1*s+1)^n;[re,im]=nyquist(g);disp([re,im]);"};
\addplot[green,thick]shell {octave -q --eval "s=tf('s');n=2;g=10/(0.1*s+1)^n;[re,im]=nyquist(g);disp([re,im]);"};
\addplot[pink,thick]shell {octave -q --eval "s=tf('s');n=3;g=10/(0.1*s+1)^n;[re,im]=nyquist(g);disp([re,im]);"};
\addplot[red,thick]shell {octave -q --eval "s=tf('s');n=4;g=10/(0.1*s+1)^n;[re,im]=nyquist(g);disp([re,im]);"};
\legend{$n-m=1$ , $n-m=2$ , $n-m=3$ , $n-m=4$}
\end{axis}
\end{tikzpicture}

** 开环系统Nyquist图,例2:$G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
 * 绘制Nyquist图,求出各特征点坐标:
 * 由于  $\nu = 1$ 
     \begin{eqnarray*}
     \lim_{\omega\rightarrow 0} A(\omega) & = & \infty\\
     \lim_{\omega\rightarrow 0} \phi(\omega)&=&-\frac{\pi}{2} \\
     \lim_{\omega\rightarrow\infty} A(\omega)&=&0 \\
     \lim_{\omega\rightarrow\infty} \phi(\omega)&=& -2\pi 
     \end{eqnarray*}
** 开环系统Nyquist图,例2(续),$G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
 概略Nyquist图:

\begin{center}
     \begin{tikzpicture}[scale=0.5]
     % $G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
     \draw[->] (-5,0) -- (1,0);
     \draw[->] (0,-5) -- (0,1);
     \draw[dashed] (-4,-5) -- (-4,0);
     \draw [red] plot [smooth] coordinates {(-4,-5) (-3.5,-3)  (-1,0) (0,0.45) (0.2,0.2) (0.1,0.01) (0,0)};
     \draw (-1,0) node[above left] {$a$};
     \draw (0,0.45) node[above right] {$b$};
     \draw (-4,0) node[above] {$v_x$};
     \end{tikzpicture}
\end{center}
** 开环系统Nyquist图,例2(续),$G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
  * 起始点实部  $v_x$:
     \begin{eqnarray*}
     G(j\omega) & = & \frac{10}{j\omega(j\omega+1)(2j\omega+1)(4j\omega+1)}\\
		&=& \frac{10\omega(8\omega^2-7)+10(14\omega^2-1)j}{\omega(1+\omega^2)(1+4\omega^2)(1+16\omega^2)}\\
     \lim_{\omega\rightarrow 0}\Re[G(j\omega)] &=&-70
     \end{eqnarray*}
** 开环系统Nyquist图,例2(续),$G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
  * 与实轴交点  $a$:
     \begin{eqnarray*}
     \Im[G(j\omega)] & = & 0\\
     \frac{10(14\omega^2-1)}{(1+\omega^2)(1+4\omega^2)(1+16\omega^2)} &=&0\\
     % 14\omega^2-1 &=& 0\\
     \omega &=& \sqrt{\frac{1}{14}}\\
     G(j\sqrt{\frac{1}{14}}) &\approx& -21.78 \\
     \end{eqnarray*}
** 开环系统Nyquist图,例2(续),$G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
  * 与虚轴交点  $b$:
     \begin{eqnarray*}
     \Re[G(j\omega)] & = & 0\\
     \frac{10\omega(8\omega^2-7)}{(1+\omega^2)(1+4\omega^2)(1+16\omega^2)} &=&0\\
     8\omega^2-7 &=& 0\\
     \omega &=& \sqrt{\frac{7}{8}}\\
     G(j\sqrt{\frac{7}{8}}) &\approx& 0.95j
     \end{eqnarray*}
** 开环系统Nyquist图,例2(续),$G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
*** Nyquist图						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <1->
     :END:
\begin{tikzpicture}[scale=0.5]
% $G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-80,ymax=10,xmin=-80,xmax=1,every axis plot post/.append style={mark=none},
grid=both]
\addplot[blue,thick]shell {octave -q --eval "s=tf('s');g=10/s/(s+1)/(2*s+1)/(4*s+1);[re,im]=nyquist(g);disp([re,im]);"};
%\draw[dashed] (axis cs:-1,-1)--(axis cs:1,-1)--(axis cs:1,1)--(axis cs:-1,1)--cycle;
\end{axis}
\end{tikzpicture}

*** 局部放大:						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:

\begin{tikzpicture}[scale=0.5]
% $G(s)=\frac{10}{s(s+1)(2s+1)(4s+1)}$ 
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-1,ymax=2,xmin=-1,xmax=1,every axis plot post/.append style={mark=none},
grid=both]
\addplot[blue,thick]shell {octave -q --eval "s=tf('s');g=10/s/(s+1)/(2*s+1)/(4*s+1);[re,im]=nyquist(g);disp([re,im]);"};
\end{axis}
\end{tikzpicture}

* 开环系统Bode图
** 开环系统Bode图
\begin{eqnarray*}
G_o(s) &=  &G_1(s)G_2(s)G_3(s)\cdots Gn(s) \\
A(\omega) &=&A_1(\omega)A_2(\omega)A_3(\omega)\cdots A_n(\omega)\\
L(\omega) &=&20\lg A_1(\omega)+\cdots+20\lg A_n(\omega) \\
\phi(\omega) &=& \phi_1(\omega)+\cdots+\phi_n(\omega)
\end{eqnarray*}

  * <2->结论:
      * <2->系统的低频段由系统的类型和开环增益  $K$  决定,代表稳态性能.由初始斜率可得系统类型.
      * <3->系统的高频段反映系统的抗噪能力,下降速度要快.

** 开环系统Bode图,例1: $G_o(s)=\frac{10(s+3)}{s(s+2)(s^2+s+2)}$ 
  绘制Bode图:
       1. <2->改写为标准形式:  $G_o(s)=\frac{7.5(\frac{s}{3}+1)}{s(0.5s+1)(0.5s^2+0.5s+1)}$ 
       2. <3->写出转折频率:  $\omega=\sqrt{2},2,3$ 
       3. <4->找到点  $(1,20\lg K)$  ,其中 $K=7.5$ 
       4. <5->过点  $(1,20\lg K)$  作斜率为  $-20dB/dec$  的直线
       5. <6->找转折点依次做直线即可
** 开环系统Bode图,例1(续): $G_o(s)=\frac{10(s+3)}{s(s+2)(s^2+s+2)}$ 
 Bode图	

              \begin{tikzpicture}[scale=0.5]
              % $G_o(s)=\frac{10(s+3)}{s(s+2)(s^2+s+2)}$ 
              \begin{semilogxaxis}[
              %axis x line=middle,axis y line= left, 
              ylabel=$L(\omega)/L_a(\omega)$ ,xlabel=$\omega$ ,
              every axis plot post/.append style={mark=none},
              grid=both,
              legend pos=south west,
              ymin=-45,ymax=20,xmin=1,xmax=10]
              \addplot[pink,thick]shell {octave -q --eval "s=tf('s');g=10*(s+3)/s/(s+2)/(2+s+s^2);[m,p,w]=bode(g);disp([w',20*log(m)/log(10)]);"};
              \addplot[red,thick] shell {
              octave -q --eval "k=10;b=[3]';a=[0 2 sqrt(2) sqrt(2)]';s=[1,sqrt(2),2,3,10];
              disp([s;20*log(k*prod(max(s,b),1)./ prod(max(s,a),1))/log(10)]');"
              };
              \legend{$L(\omega)$ , $L_a(\omega)$};
              \end{semilogxaxis}
              \end{tikzpicture}
              \begin{tikzpicture}[scale=0.5]
              % $G_o(s)=\frac{10(s+3)}{s(s+2)(s^2+s+2)}$ 
              \begin{semilogxaxis}[
              %axis x line=middle,axis y line= left, 
              ylabel=$\phi(\omega)$ ,xlabel=$\omega$ ,
              every axis plot post/.append style={mark=none},
              grid=both,
              legend pos=south west,
              ymin=-270,ymax=-90,xmin=1,xmax=10]
              %\draw[blue,thick] (axis cs:0.1,90)--(axis cs:10,90);
              \addplot[violet,thick]shell {octave -q --eval "s=tf('s');g=10*(s+3)/s/(s+2)/(2+s+s^2);[m,p,w]=bode(g);disp([w',p]);"};
              \end{semilogxaxis}
              \end{tikzpicture}

	      \mode<article>{ $(1,20\lg K)$ 在  $L(\omega)$  上或在其延长线上}
