# +LaTeX_CLASS:  article
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}
#+LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}


#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [table]
# +LaTeX_CLASS_OPTIONS: [bigger]
#+latex_header:  \mode<article>{\usepackage{beamerarticle}}
# +latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
# +latex_header: \mode<beamer>{\usetheme{Boadilla}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}
#+latex_header: \mode<beamer>{\AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}}
#+latex_header: \setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 3
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+TITLE:  线性系统的频域分析法
#+latex_header: \subtitle{频域稳定性判据与闭环频率特性}
#+AUTHOR:    
#+EMAIL: 
#+DATE:  
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* 频域稳定性判据
** Nyquit稳定性判据
*** 辐角原理
 * 设  $s$  为复变量,  $F(s)$  为  $s$  的有理分式函数.对于  $s$  平面上任意一点  $s$  , 通过复变函数  $F(s)$  的映射关系,可以确定  $s$  的象.
 * 在  $s$  平面上任选一条闭合曲线  $\Gamma$  ,且不通过  $F(s)$  任一零点和极点,  $s$  沿闭合曲线  $\Gamma$  运动一周,则相应地  $F(s)$  形成一条闭合曲线  $\Gamma_F$ .
 * 辐角原理:设  $s$  平面闭合曲线  $\Gamma$  包围  $F(s)$  的  $Z$  个零点和  $P$  个极点,则  $s$  沿  $\Gamma$  顺时针运动一周时,在  $F(s)$  平面上,  $F(s)$  沿闭合曲线  $\Gamma_F$  逆时针包围原点的圈数为  $R=P-Z$ .

\begin{tikzpicture}
\draw[->] (-1,0) -- (4.5,0);
\draw[->] (0,-2) -- (0,2);
\draw (0,2) node[above left] {$j$};
\draw (2,2) node[above right] {$\Gamma$};
%\draw[dashed] (-4,-5) -- (-4,0);
\draw [red] plot [smooth] coordinates {(1,0.5) (2,2)  (3,1.5) (3.5,0) (1.1,0) (1,0.5)};
\draw (1,0.5) node {$\cdot$};
\draw (1,0.5) node[left] {$s$};
\draw[blue,->,thick] (1,0.5)-- ++(0.3,0.6);
\draw (2,1) node {$\times$};
\draw (2,-1) node {$\times$};
\draw (2.3,0) node {$\times$};
\draw (2.7,0.3) node {$\circ$};
\draw (2.7,-0.3) node {$\circ$};

\begin{scope}[shift={(7,0)}]
\draw[->] (-2,0) -- (2,0);
\draw[->] (0,-2) -- (0,2);
\draw (0,2) node[above left] {$j$};
\draw (1,1) node[above right] {$\Gamma_F$};
\draw[red] (0,0) ++(0:1) arc (0:360:1);
\draw[thick] (120:1) node {$\cdot$};
\draw (120:1) node[above left] {$F(s)$};
\draw (0,0) node[below left] {$o$};
\draw[blue,->,thick] (120:1)-- ++(-0.3,-0.2);
\end{scope}
\end{tikzpicture}

*** 辐角原理的应用:传递函数
\begin{eqnarray*}
\Phi(s) &= &\frac{G(s)}{1+G(s)H(s)} \\
       &=&\frac{G(s)}{1+G_o(s)} \\
       &=&\frac{G(s)}{F(s)} \\
 F(s)&=&1+G_o(s)
\end{eqnarray*}
  * $F(s)$  的极点是系统开环极点,  
  * $F(s)$  的零点是系统的闭环极点.

*** 辐角原理的应用: $F(s)=1+G_o(s)$
**** 示意图					      :B_ignoreheading:BMCOL:
     :PROPERTIES:
     :BEAMER_env: ignoreheading
     :BEAMER_col: 0.2
     :END:
\begin{tikzpicture}
\draw[->] (-0.1,0) -- (2,0);
\draw[->] (0,-2) -- (0,2);
\draw (0,2) node[above left] {$j$};
\draw (0,0) node[below left] {$o$};
\draw[red,thick,->] (0,-1.7) -- (0,1.7);
\draw[violet,dashed,->] (0,2) arc (90:-90:2);
\draw[green,thick,->] (0,0) -- (60:2);
\draw (60:2) node[above] {$R$};
\draw (0,1) node[left] {$\Gamma_1$};
\draw (45:2) node[right] {$\Gamma_2$};
\end{tikzpicture}

**** 将 $\Gamma$ 分为两段:				      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.8
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
  * $\Gamma_1$ : $s=j\omega,\omega\in[-\infty,\infty]$ 
  * $\Gamma_2$ : $s=\lim_{R\rightarrow\infty}Re^{j\theta}$ , $\theta$ 从 $\frac{\pi}{2}$ 到 $-\frac{\pi}{2}$ 
  * 可得对应的 $G_o(s)$ 曲线.
    *  $s$ 在 $\Gamma_1$ 上时,与Nyquist图对应.($\omega\in[0,\infty]$)
    *  $s$ 在 $\Gamma_1$ 上时, $F(s)=1+G_o(s)=1+\lim_{R\rightarrow\infty}Re^{j\theta}G_o(s)=1$ 
  * <3-> Nyquist判据
     * 对于开环稳定系统($P=0$),若Nyquist曲线不包含 $(-1,0)$ 点,则系统稳定.
     * 对于开环稳定系统($P>0$),若Nyquist曲线逆时针包围 $(-1,0)$ 点的次数为 $\frac{P}{2}$ ,则系统稳定.

*** Nyquist判据,例1: 
某负反馈开环传递函数为 $G_o(s)=\frac{10}{s-1}$ ,用Nyquist判据判断系统稳定性.

**** Nyquist图 						      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.5
    :BEAMER_env: block
    :END:
\begin{tikzpicture}[scale=0.5]
%g=10/(s-1)
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-5.7,ymax=1,xmin=-11,xmax=1,every axis plot post/.append style={mark=none},
grid=both]
\addplot[blue,thick,->]
shell {
octave -q --eval "s=tf('s');g=10/(s-1);[re,im]=nyquist(g);disp([re,im]);"
};
\end{axis}
\end{tikzpicture}

**** 稳定性判断 					      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
\begin{eqnarray*}
P & = & 1\\
N &=& \frac{1}{2} \\
P-Z &=& 2N \\
Z &=& P-2N \\
  &=&0 
\end{eqnarray*}
系统稳定.

*** 虚轴上有极点时
 * 零型系统 $F(s)$ 沿 $\Gamma$ 解析且不为0.
 * I型及以上系统 $F(s)$ 在 $s=0$ 处不解析,不满足辐角原理条件.

**** 示意图					      :B_ignoreheading:BMCOL:
     :PROPERTIES:
     :BEAMER_env: ignoreheading
     :BEAMER_col: 0.5
     :END:
\begin{tikzpicture}
\draw[->] (-1,0) -- (2,0);
\draw[->] (0,-2) -- (0,2);
\draw (0,2) node[above left] {$j$};
\draw (0,0) node[below left] {$o$};
\draw[red,thick,->] (0,0.5) -- (0,1.7);
\draw[red,thick,->] (0,-1.7) -- (0,-0.5);
\draw[blue,thick,->] (0,0)++(-90:0.5) arc (-90:90:0.5);
\draw[violet,dashed,->] (0,2) arc (90:-90:2);
\draw[green,thick,->] (0,0) -- (60:0.5);
\draw (60:0.5) node[above] {$\epsilon$};
\draw (0,1) node[left] {$\Gamma_2$};
\draw (45:0.5) node[right] {$\Gamma_0$};
\draw (0,-1) node[left] {$\Gamma_1$};
\draw (45:2) node[right] {$\Gamma_3$};
\end{tikzpicture}

**** 将 $\Gamma$ 分为四段:				      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
  *  $\Gamma_1$ : $s=j\omega,\omega\in[-\infty,0^-]$ 
  *  $\Gamma_2$ : $s=j\omega,\omega\in[0^+,\infty]$ 
  *  $\Gamma_3$ : $s=\lim_{R\rightarrow\infty}Re^{j\theta},\theta\in[-\frac{\pi}{2},\frac{\pi}{2}]$ 
  *  $\Gamma_0$ : $s=\lim_{\epsilon\rightarrow 0}\epsilon^{j\theta}$ , $\theta$ 从 $\frac{\pi}{2}$ 到 $-\frac{\pi}{2}$ 
  *  <3->对增补后的Nyquist图可使用Nyquist判据.

*** 穿越次数
**** Nyquist图						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :END:
\begin{tikzpicture}[scale=0.5]
\begin{axis}[
axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-2.5,ymax=1,xmin=-3.5,xmax=3.5,every axis plot post/.append style={mark=none}]
grid=both,
\addplot[smooth,blue,thick,->]
shell {
octave -q --eval "
a=[0.01 3   0;
   0.1  0   -2; 
   1   -3   0; 
   2   -2.3  0.5; 3 -1.7 0; 4 -1 -0.5; 3 -0.5 0 ;5 -0.25 0.25; 7 0 0];
disp(a(:,2:3));"};
\end{axis}
\end{tikzpicture}

**** 穿越次数						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :END:
  * 根据增补后的Nyquist曲线穿越 $(-1,0)$ 点左侧的次数可得 $\Gamma_F$ 包围原点的圈数
      \begin{eqnarray*}
      R &=  &2N \\
        &=& 2(N_+ - N_-)
      \end{eqnarray*}
      * 其中,
            *  $N_+$ 为正穿越(自上向下)次数
            *  $N_-$ 为负穿越(自下向上)次数

*** 例: $G_o(s)=\frac{10}{s(s+1)}$ 

\begin{tikzpicture}
%g=10/s/(s+1)
\begin{axis}[
axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-9,ymax=1,xmin=-6,xmax=10,every axis plot post/.append style={mark=none}]
grid=both,
\addplot[blue,thick,->]
shell {
octave -q --eval "s=tf('s');g=10/s/(s+1);[re,im]=nyquist(g);disp([re,im]);"
};
\addplot[red,dashed,->]shell {octave -q --eval "t=[-0.1:-0.1:-pi*1.5/2]';disp(8*[cos(t),sin(t)]);"};
\end{axis}
\end{tikzpicture}

** Bode稳定性判据
*** Bode稳定性判据
**** Bode图					      :BMCOL:B_ignoreheading:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: ignoreheading
     :END:
\begin{tikzpicture}[scale=0.42]
\begin{semilogxaxis}[
%axis x line=middle,axis y line= left, 
ylabel=$L(\omega)/L_a(\omega)$ ,xlabel=$\omega$ ,
every axis plot post/.append style={mark=none},
grid=both,
ymin=-10,ymax=20,xmin=0.01,xmax=10]
\addplot[smooth,blue,thick]
 shell {
octave -q --eval "
a=[0.01 3   0;
   0.1  0   -2; 
   1   -3   0; 
   2   -2.3  0.5; 
   3 -1.7 0;
   5 -1 -0.5;
   7 -0.5 0 ;
   10 -0.25 0.25];
w=a(:,1);
a=a(:,2)+i*a(:,3);
m=abs(a);
disp([w,20*log(m)/log(10)]);"};
\end{semilogxaxis}
\end{tikzpicture}
\begin{tikzpicture}[scale=0.42]
\begin{semilogxaxis}[
%axis x line=middle,axis y line= left, 
ylabel=$\phi(\omega)$ ,xlabel=$\omega$ ,
every axis plot post/.append style={mark=none},
grid=both,
ymin=-200,ymax=10,xmin=0.01,xmax=11]
%\draw[blue,thick] (axis cs:0.1,90)--(axis cs:10,90);
\addplot[smooth,blue,thick]
shell {
octave -q --eval "
a=[0.01 3   0;
   0.1  0   -2; 
   1   -3   0; 
   2   -2.3  0.5; 
   3 -1.7 0;
   5 -1 -0.5;
   7 -0.5 0 ;
   10 -0.25 0.25];
w=a(:,1);
a=a(:,2)+i*a(:,3);
p=angle(a)*180/pi;
p(p>0)=p(p>0)-360;
disp([w,p]);"};
\draw[red,dashed] (axis cs:0.01,-180) --(axis cs:10,-180);
\draw[red,dashed] (axis cs:5,-190) --(axis cs:5,-170);
\end{semilogxaxis}
\end{tikzpicture}
\begin{tikzpicture}[scale=0.42]
\begin{axis}[
%axis x line=middle,axis y line= middle, 
ylabel=$j$ ,xlabel=$   $ ,
ymin=-2.5,ymax=1,xmin=-3.5,xmax=3.5,every axis plot post/.append style={mark=none},
grid=both]
\addplot[smooth,blue,thick,->]
shell {
octave -q --eval "
a=[0.01 3   0;
   0.1  0   -2; 
   1   -3   0; 
   2   -2.3  0.5; 3 -1.7 0; 4 -1 -0.5; 3 -0.5 0 ;5 -0.25 0.25; 7 0 0];
disp(a(:,2:3));"};
\end{axis}
\end{tikzpicture}

**** 稳定性判断						      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.5
     :BEAMER_env: block
     :BEAMER_envargs: <2->
     :END:
  * 截止频率 $\omega_c$ : $A(\omega_c)=0$ 
  * 穿越频率 $\omega_x$ : $\phi(\omega_x)=(2k+1)\pi$ 
  * <3->Bode判据:
      * 最小相位系统,若在 $\omega<\omega_c$ 前 $N_+-N_-=0$ ,则系统稳定
      * 非最小相位系统,若在 $\omega<\omega_c$ 前 $N_+-N_-=\frac{P}{2}$ ,则系统稳定

** 稳定裕度
*** 稳定裕度
 * 相角裕度 $\gamma$ : $\gamma=180+\phi(\omega_c)$ 
 * 幅值裕度 $h$ : $h=-20\lg A(\omega_g)$ 
 * <2->例: $G_o(s)=\frac{100(s+4)}{s(s+1)(s+2)(s+3)}$ 近似计算求解 $\omega_c$ 
   *  <3->$\omega_c<1$   时, $A(\omega)=\frac{200}{3}\cdot\frac{1}{\omega_c}$ , $\omega_c=\frac{200}{3}>2$ 矛盾.
   *  <4->$1<\omega_c<2$ 时, $A(\omega)=\frac{200}{3}\cdot\frac{1}{\omega_c\cdot\omega_c}$ , $\omega_c=\sqrt{\frac{200}{3}}>2$ 矛盾.
   *  <5->$2<\omega_c<3$ 时, $A(\omega)=\frac{200}{3}\cdot\frac{1}{\omega_c\cdot\omega_c\cdots\frac{\omega_c}{2}}$ , $\omega_c=\sqrt[3]{\frac{400}{3}}>3$ 矛盾.
   *  <6->$2<\omega_c<3$ 时, $A(\omega)=\frac{200}{3}\cdot\frac{1}{\omega_c\cdot\omega_c\cdots\frac{\omega_c}{2}\cdots\frac{\omega_c}{3}}$ , $\omega_c=\sqrt[4]{400}>4$ 矛盾.
   *  <7->$2<\omega_c<3$ 时, $A(\omega)=\frac{200}{3}\cdot\frac{\frac{\omega_c}{4}}{\omega_c\cdot\omega_c\cdots\frac{\omega_c}{2}\cdots\frac{\omega_c}{3}}$ , $\omega_c=\sqrt[3]{100}>4$ 成立.

* 闭环频率特性
** 频带宽度
*** 频带宽度
 * 设闭环系统频率特性为 $\Phi(j\omega)$ , 若 $\omega>\omega_b$ 时,有 $20\lg|\Phi(j\omega)| <20\lg|\Phi(j0)|-3$ ,则称 $\omega_b$ 为带宽频率.

      \begin{tikzpicture}
      \draw[->] (-1,0) -- (4.5,0);
      \draw[->] (0,-0.5) -- (0,2);
      %\draw[dashed] (-4,-5) -- (-4,0);
      \draw [red] plot [smooth] coordinates {(0,1) (1,1)  (2,1.2) (2.5,0.70795) (3,0.2) };
      \draw (0,1) node[left] {$1$};
      \draw (0,0) node[below left] {$o$};
      \draw[pink,dashed] (2,0)-- ++(0,1.2);
      \draw (2,0) node[below] {$\omega_r$};
      \draw[pink,dashed] (0,1.2)--++(2,0);
      \draw (0,1.2) node[above left] {$M_r$};
      \draw[blue,dashed] (2.5,0)-- ++(0,0.70795);
      \draw (2.5,0) node[below] {$\omega_b$};
      \draw[blue,dashed] (0,0.70795)--++(2.5,0);
      \end{tikzpicture}
* 指标转换
** 2阶系统
*** 2阶系统指标转换
\begin{eqnarray*}
M_r & = &\frac{1}{2\xi\sqrt{1-\xi^2}} \\
\omega_r &=& \omega_n\sqrt{1-2\xi^2}
\end{eqnarray*}
 * <2->$M_r$ 与 $\sigma\%$ 一一对应,且成正比

** 高阶系统
*** 高阶系统经验公式
**** 经验公式					      :BMCOL:B_ignoreheading:
     :PROPERTIES:
     :BEAMER_col: 0.7
     :BEAMER_env: ignoreheading
     :END:
\begin{eqnarray*}
M_r & = & \frac{1}{\sin\gamma}\\
\sigma\% &=& 16\%+0.4(M_r-1), (1\leq M_r\leq 1.8) \\
t_s &=& \frac{K\pi}{\omega_c}\\
K&=& 2+1.5(M_r-1)+2.5(M_r-1)^2 
\end{eqnarray*}

 *  <2->$\gamma\uparrow \rightarrow \sigma\%\downarrow \rightarrow \xi\uparrow$  一一对应
 *  <3->$\omega_c\uparrow \rightarrow t_s\downarrow$ (快速性)

**** 频域三段论:					      :BMCOL:B_block:
     :PROPERTIES:
     :BEAMER_col: 0.3
     :BEAMER_env: block
     :BEAMER_envargs: <4->
     :END:
 * 低频段:稳态性能
 * 中频段:瞬态性能
 * 高频段:抗干扰能力
