# +LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage{etex}
#+LATEX_HEADER: \usepackage{amsmath}
 # +LATEX_HEADER: \usepackage[usenames]{color}
#+LATEX_HEADER: \usepackage{pstricks}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage[europeanresistors,americaninductors]{circuitikz}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{yfonts}
#+LATEX_HEADER: \usetikzlibrary{shapes,arrows}
#+LATEX_HEADER: \usetikzlibrary{positioning}
#+LATEX_HEADER: \usetikzlibrary{arrows,shapes}
#+LATEX_HEADER: \usetikzlibrary{intersections}
#+LATEX_HEADER: \usetikzlibrary{calc,patterns,decorations.pathmorphing,decorations.markings}
#+LATEX_HEADER: \usepackage[BoldFont,SlantFont,CJKchecksingle]{xeCJK}
#+LATEX_HEADER: \setCJKmainfont[BoldFont=Evermore Hei]{Evermore Kai}
#+LATEX_HEADER: \setCJKmonofont{Evermore Kai}
 # +LATEX_HEADER: \xeCJKsetup{CJKglue=\hspace{0pt plus .08 \baselineskip }}
#+LATEX_HEADER: \usepackage{pst-node}
#+LATEX_HEADER: \usepackage{pst-plot}
#+LATEX_HEADER: \psset{unit=5mm}

#+startup: beamer
#+LaTeX_CLASS: beamer
# +LaTeX_CLASS_OPTIONS: [bigger]
 # +latex_header: \usepackage{beamerarticle}
# +latex_header: \mode<beamer>{\usetheme{JuanLesPins}}
#+latex_header: \mode<beamer>{\usetheme{Frankfurt}}
#+latex_header: \mode<beamer>{\usecolortheme{dove}}
#+latex_header: \mode<article>{\hypersetup{colorlinks=true,pdfborder={0 0 0}}}

#+TITLE:  自动控制的基本概念
#+AUTHOR:    
#+EMAIL:
#+DATE:
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}

#+latex_header:\setbeamercovered{transparent}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)












# * 控制方式
# ** 控制方式
#    共有三种
#    * 开环控制
#    * 闭环控制
#    * 复合控制

* 开环控制
**  开环控制
 * <2->定义：开环控制是指控制器与被控对象之间只有顺向作用而没有反向联系，称为开环控制。
 * <3->系统的输出量对系统的输入量无影响
 * <4->开环系统对控制偏差无修正能力。
    * <5->按给定量控制
    * <6->按扰动量控制

** 按给定量控制

# #+begin_example
#   电压 U_g ---> 信号变换与驱动电路 ---> 电机 --->  转速 n
# #+end_example

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$U_g$}; 
%\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
%\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of r] (n) {信号变换与驱动电路}; 
\path[->] (r) edge node[midway] {} (n) ; 
\path[red] node[draw, inner sep=5pt,right =of n] (g) {电机}; 
\path[->] (n) edge node [midway]{$ $} (g); 
\path[->] node[ right =of g] (o) {$n$}; 
\path[->] (g) edge node {} (o); 
%\path[blue] node[draw, below =of g] (h) {传感器};
%\path[->,draw] (g.east)+(1em,0) |- (h.east) ; 
%\path[->,draw] (h.west) -| (p1) ; 
\end{tikzpicture} 

  * 输入量: 电压 $U_g$
  * 输出量: 电机转速 $n$
  * $n=kU_g$
** 按扰动量控制
   对扰动进行补偿,使扰动的影响减小

# #+begin_example 
#   电压            U_c
#          U_0 -->O-->驱动电路 ---> 电机 --->  转速 n
#                 ^                  :
#             U_b |                  :
#                 +---扰动测量<---负载扰动
# #+end_example

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$U_0$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of p1] (n) {驱动电路}; 
\path[->] (p1) edge node[midway] {$U_c$} (n) ; 
\path[red] node[draw, inner sep=5pt,right =of n] (g) {电机}; 
\path[->] (n) edge node [midway]{$ $} (g); 
\path[->] node[ right =of g] (o) {$n$}; 
\path[->] (g) edge node {} (o); 
\path[blue] node[draw, below =of g] (l) {负载扰动};
\path[dashed,draw] (g.south) edge (l) ; 
\path[blue] node[draw, below =of n] (h) {扰动测量};
\path[->,draw] (l) edge  node[midway] {$i$} (h) ; 
\path[->,draw] (h.west) -| node[midway]{$U_b$} (p1) ; 
\end{tikzpicture} 

    * $U_c=U_0+U_b$
    * 负载增加导致 $n\downarrow , i\uparrow$
    * $i\uparrow\rightarrow U_b\uparrow\rightarrow U_c\uparrow\rightarrow n\uparrow$

** 开环控制特点
   1. <2->优点：原理简单,结构简单,反应速度快,灵敏度高
   1. <3->缺点：
      * 对控制偏差无修正能力
      * 控制精度取决于各控制元器件的精度
   1. <4->适应场合：对控制精度要求不高的系统
   1. <5-> 结构图：   输入 $\rightarrow$ 控制器 $\rightarrow$ 被控对象 $\rightarrow$ 输出  （顺向作用）

* 闭环控制
** 闭环控制
#  #+begin_example
#                   e(t)
#    r(t) --->(+/-)----> controller ----> plant  ------> c(t)
#               ^                                   |
#               |                                   |
#                ------------    sensor <-----------
#  #+end_example

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {期望}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of p1] (n) {控制器}; 
\path[->] (p1) edge node[midway] {偏差} (n) ; 
\path[red] node[draw, inner sep=5pt,right =of n] (g) {被控对象}; 
\path[->] (n) edge node [midway]{$ $} (g); 
\path[->] node[ right =of g] (o) {输出}; 
\path[->] (g) edge node {} (o); 
\path[blue] node[draw, below =of g] (h) {传感器};
\path[->,draw] (g.east)+(1em,0) |- (h.east) ; 
\path[->,draw] (h.west) -| (p1) ; 
\end{tikzpicture} 

  * <2-> 定义： 闭环控制是指在输出量处,通过 *反馈* 回路使得输出量对输入量施加影响
  * <3-> 控制目的：通过在输入端引入输出量,使得输入处的偏差 $\rightarrow0$
  * <4->闭环控制按偏差进行调节。

** 反馈
     * 反馈: 指将系统的输出返回到输入端并以某种方式改变输入，进而影响系统功能的过程。
     * 正反馈: 输出变化时,反馈对输出造成的影响与输出变化趋势相同
     * 负反馈：输出变化时,反馈对输出造成的影响与输出变化趋势相反
**  示例：人手工竖杆
*** 示意图						      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.3
    :BEAMER_env: block
    :END:
# +begin_example
#  
#     θ 
#    \  :
#     \ :
#      \: O
#       `-|>
#        / \
# +end_example


#  #+ATTR_LATEX: height=0.5\textheight
# [ [file:image/rod.pdf] ]

\input{image/rod.tex}

*** 分析						      :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.7
    :BEAMER_env: block
    :END:
\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {0}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of p1] (n) {脑}; 
\path[->] (p1) edge node[midway] {偏差} (n) ; 
\path[blue] node[draw, right =of n] (d) {手}; 
\path[->] (n) edge node[midway] {} (d) ; 
\path[red] node[draw, inner sep=5pt,right =of d] (g) {杆}; 
\path[->] (d) edge node [midway]{$ $} (g); 
\path[->] node[ right =of g] (o) {$\theta$}; 
\path[->] (g) edge node {} (o); 
\path[blue] node[draw, below =of d] (h) {眼};
\path[->,draw] (g.east)+(1em,0) |- (h.east) ; 
\path[->,draw] (h.west) -| (p1) ; 
\end{tikzpicture} 


  * 反馈通道：眼
  * 执行机构：手
  * 被控制量：杆与竖直方向夹角  $\theta\rightarrow 0$

**  示例：倒立摆系统

# +begin_example
#    
#               θ 
#              \  :
#               \ :
#                \:
#       r         * 
#  @-----------[######]------------@
#  |             o  o              |
#  #===============================#
# +end_example

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[blue] node[draw, right =of n] (d) {电机}; 
\path[red] node[draw, inner sep=5pt,right =of d] (g) {小车}; 
\path[red,draw] (g.south)+(-0.7em,-0.25em) circle (0.25em) (g.south)+(0.7em,-0.25em) circle (0.25em);
\path[red,draw] (g.north)--+(60:3em);
\path[draw,dashed] (g.north)--+(90:3em);
\path[draw,dashed] (g.north)++(90:2.5em) arc (90:60:2.5em);
\path  (g.north)+(75:3em) node {$\theta$};
\path[] (d) edge node [midway]{$ $} (g); 
\path[blue] node[draw, right =of g] (h) {传感器};
\path[] (g) edge node {$\theta,r$}(h) ; 
\path[red,draw] (d.south)|-($(g.south)+(0,-0.51em)$)-| (h.south);

\path[blue] node[draw, below =of g] (n) {控制器}; 
\path[<-,draw] (d.west)--+(-1em,0) |- (n.west) ; 
\path[->,draw] (h.east)--+(1em,0) |- (n.east) ; 
\end{tikzpicture} 


   * 执行机构：电机
   * 反馈通道：角度传感器、位置传感器
   * 被控制量： $\theta\rightarrow 0, r\rightarrow 0$

**  示例：直流电机速度反馈控制系统

# +begin_example
#  + o---.
#        |
#        $ (Ug)    .---------.    .--------.   .----------.
#  (E)   $<--------+         +----+        +---+          |
#        $    (Ud) |Amplifier|    | Driver |   | Dc Motor |
#        $     .---+         +----+        +---+          |
#        $     |   '---------'    '--------'   '----@-----'
#        |     |                                    |  (n)
#  - o---+     |                 (Uf)    .----------@------------.
#        |     '-------------------------+ Speed Measuring Motor |
#        |                               '----------+------------'
#        |                                          |
#         '------------------------------------------'
# +end_example

\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$U_g$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of p1] (n) {放大器}; 
\path[->] (p1) edge node[midway] {$U_d$} (n) ; 
\path[red] node[draw, inner sep=5pt,right =of n] (d) {驱动电路}; 
\path[->] (n) edge node [midway]{$ $} (d); 
\path[red] node[draw, inner sep=5pt,right =of d] (g) {电机}; 
\path[->] (d) edge node [midway]{$ $} (g); 
\path[red] node[draw, inner sep=5pt,below =of g] (s) {测速电机};
\path[red] (g) edge node {$n$} (s); 
\path[->,draw] (s.west) -| node[near start] {$U_f$} node[very near end] {$-$} (p1) ; 
\end{tikzpicture} 

\begin{eqnarray}
  n  &=& K U_d \\
  U_d &=& U_g-U_f \\
  U_f &=& K' n
\end{eqnarray}

负载增大后: $n\downarrow\rightarrow U_f\downarrow\rightarrow U_d\uparrow\rightarrow n\uparrow$

** 负反馈放大器
\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {r}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of p1] (g) {$K$}; 
\path[->] (p1) edge node[midway] {$e$} (g) ; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of g] (p2) { }; 
\path[->] (g) edge node [midway]{$ $} (p2); 
\path[->] node[ right =of p2] (o) {$c$}; 
\path[->] (p2) edge node {} (o); 

\path[blue] node[draw, below =of g] (h) {$A$};
\path[->,draw] (p2.east)+(1em,0) |- (h.east) ; 
\path[->,draw] (h.west) -| (p1) ; 

\path[blue] node[ above =of p2] (f) {$f$};
\path[->] (f) edge node [midway]{$ $} (p2); 
\end{tikzpicture} 

\begin{eqnarray}
c &=& Ke+f \\
e &=& r-Ac \\
c &=& \frac{Kc}{1+KA}+\frac{f}{1+KA}
\end{eqnarray}

** 闭环控制的特点
 1. <2->按偏差进行调节
 1. <3->控制精度较高，取决于反馈通道元器件的精度，而反馈通道所包围的电路中的元器件的元件精度可降低
 1. <4->抗干扰能力强
# 1. <5->灵敏度较开环差
# 1. <6->若设计不当，会出现发散现象（不稳定）

**  复合控制
扰动补偿+闭环控制

例：直流电机速度复合控制

# +begin_example
#    + o----.
#            |
#            $ (Ug)    .---------.       .--------.         .----------.
#     (E)    $<--------+         +-------+        +---------+          |
#            $    (ΔU) |Amplifier|       | Driver |         | Dc Motor |
#            $     .---+         +-.   .-+        +---+[R]+-+          |
#            $     |   '---------' |   | '--------'   |   | '---@------'
#            |     |               |   |  .---------. |   |     | 
#     - o----+     |               |   `--+         +-'   |     |
#            |     |               `------+reifilpmA+-----'     | (n)
#            |     |                      '---------'           | 
#            |     |                 (Uf)    .------------------@----.
#            |     '-------------------------+ Speed Measuring Motor |
#            |                               '----------+------------'
#            |                                          |
#            '------------------------------------------'
# +end_example
\begin{tikzpicture}[node distance=2em,auto,>=latex', thick]
\tikzstyle{every node}=[font=\small]
%\path[use as bounding box] (-1,0) rectangle (10,-2); 
\path[->] node[] (r) {$U_g$}; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of r] (p1) { }; 
\path[->](r) edge node {} (p1) ; 
\path[blue] node[draw, right =of p1] (n) {放大器}; 
\path[->] (p1) edge node[midway] {$U_d$} (n) ; 
\path[->] node[ circle,inner sep=2pt,minimum size=1pt,draw,label=below left:$ $,right =of n] (p2) { }; 
\path[->](n) edge node {} (p2) ; 
\path[red] node[draw, inner sep=5pt,right =of p2] (d) {驱动电路}; 
\path[->] (p2) edge node [midway]{$ $} (d); 
\path[red] node[draw, inner sep=5pt,right =of d] (g) {电机}; 
\path[->] (d) edge node [midway]{$ $} (g); 
\path[red] node[draw, inner sep=5pt,below =of g] (s) {测速电机};
\path[red] (g) edge node {$n$} (s); 
\path[->,draw] (s.west) -| node[near start] {$U_f$} node[very near end] {$-$} (p1) ; 

\path[blue] node[draw, above =of g] (l) {负载扰动};
\path[dashed,draw] (g.north) edge (l) ; 
\path[blue] node[draw, left =of l] (h) {扰动测量};
\path[->,draw] (l) edge  node[midway] {$i$} (h) ; 
\path[->,draw] (h.west) -| node[near end]{$U_b$} (p2) ; 
\end{tikzpicture} 

