a=[1:100];
b=a^2;
c=[b,b(100:-1:1)];
plot(c)
f=fft(c);
plot(abs(f),'.-')
d=c-sum(c)/length(c);
f=fft(c);
f1=fft(d);
plot(abs(f),'.-')
plot(d)
plot(abs(ifft(f)))
plot(real(ifft(f)))
f2=f;
f2(50:150)=0;
plot(abs(f2),'.-')
plot(real(ifft(f2)))
plot(real(ifft(f2))-real(ifft(f1)))
                            
